/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  OrdersApi,
  TrackersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PayPalCheckoutCustom } from "./client-custom";

export class PayPalCheckout extends PayPalCheckoutCustom {
  readonly orders: OrdersApi;
  readonly trackers: TrackersApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.orders = new OrdersApi(configuration);
    this.trackers = new TrackersApi(configuration);
  }

}
