/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressDetailsProperty1 } from './address-details-property1';

/**
 * The portable international postal address. Maps to [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls: the autocomplete attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute).
 * @export
 * @interface AddressPortable2
 */
export interface AddressPortable2 {
    /**
     * The first line of the address, such as number and street, for example, `173 Drury Lane`. Needed for data entry, and Compliance and Risk checks. This field needs to pass the full address.
     * @type {string}
     * @memberof AddressPortable2
     */
    'address_line_1'?: string;
    /**
     * The second line of the address, for example, a suite or apartment number.
     * @type {string}
     * @memberof AddressPortable2
     */
    'address_line_2'?: string;
    /**
     * The third line of the address, if needed. Examples include a street complement for Brazil, direction text, such as `next to Walmart`, or a landmark in an Indian address.
     * @type {string}
     * @memberof AddressPortable2
     */
    'address_line_3'?: string;
    /**
     * The neighborhood, ward, or district. This is smaller than `admin_area_level_3` or `sub_locality`. Value is:<ul><li>The postal sorting code that is used in Guernsey and many French territories, such as French Guiana.</li><li>The fine-grained administrative levels in China.</li></ul>
     * @type {string}
     * @memberof AddressPortable2
     */
    'admin_area_4'?: string;
    /**
     * The sub-locality, suburb, neighborhood, or district. This is smaller than `admin_area_level_2`. Value is:<ul><li>Brazil. Suburb, *bairro*, or neighborhood.</li><li>India. Sub-locality or district. Street name information isn\'t always available, but a sub-locality or district can be a very small area.</li></ul>
     * @type {string}
     * @memberof AddressPortable2
     */
    'admin_area_3'?: string;
    /**
     * A city, town, or village. Smaller than `admin_area_level_1`.
     * @type {string}
     * @memberof AddressPortable2
     */
    'admin_area_2'?: string;
    /**
     * The highest-level sub-division in a country, which is usually a province, state, or ISO-3166-2 subdivision. This data is formatted for postal delivery, for example, `CA` and not `California`. Value, by country, is:<ul><li>UK. A county.</li><li>US. A state.</li><li>Canada. A province.</li><li>Japan. A prefecture.</li><li>Switzerland. A *kanton*.</li></ul>
     * @type {string}
     * @memberof AddressPortable2
     */
    'admin_area_1'?: string;
    /**
     * The postal code, which is the ZIP code or equivalent. Typically required for countries with a postal code or an equivalent. See [postal code](https://en.wikipedia.org/wiki/Postal_code).
     * @type {string}
     * @memberof AddressPortable2
     */
    'postal_code'?: string;
    /**
     * The [2-character ISO 3166-1 code](https://raw.githubusercontent.com) that identifies the country or region.<blockquote><strong>Note:</strong> The country code for Great Britain is <code>GB</code> and not <code>UK</code> as used in the top-level domain names for that country. Use the `C2` country code for China worldwide for comparable uncontrolled price (CUP) method, bank card, and cross-border transactions.</blockquote>
     * @type {string}
     * @memberof AddressPortable2
     */
    'country_code': string;
    /**
     * 
     * @type {AddressDetailsProperty1}
     * @memberof AddressPortable2
     */
    'address_details'?: AddressDetailsProperty1;
}

