/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The non-portable additional address details include fine-grain address information for Compliance, Risk, and other scenarios. This isn\'t portable with common third-party and open source applications. This can include data that is redundant with core fields. For example, `address_portable.address_line_1` is usually a combination of `address_details.street_number`, `street_name`, and `street_type`.
 * @export
 * @interface AddressDetailsProperty1
 */
export interface AddressDetailsProperty1 {
    /**
     * The street number.
     * @type {string}
     * @memberof AddressDetailsProperty1
     */
    'street_number'?: string;
    /**
     * The street name. Just `Drury` in `Drury Lane`.
     * @type {string}
     * @memberof AddressDetailsProperty1
     */
    'street_name'?: string;
    /**
     * The street type. For example, avenue, boulevard, road, or expressway.
     * @type {string}
     * @memberof AddressDetailsProperty1
     */
    'street_type'?: string;
    /**
     * The delivery service. Post office box, bag number, or post office name.
     * @type {string}
     * @memberof AddressDetailsProperty1
     */
    'delivery_service'?: string;
    /**
     * A named locations that represents the premise. Usually a building name or number or collection of buildings with a common name or number. For example, <code>Craven House</code>.
     * @type {string}
     * @memberof AddressDetailsProperty1
     */
    'building_name'?: string;
    /**
     * The first-order entity below a named building or location that represents the sub-premise. Usually a single building within a collection of buildings with a common name. Can be a flat, story, floor, room, or apartment.
     * @type {string}
     * @memberof AddressDetailsProperty1
     */
    'sub_building'?: string;
}

