/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The non-portable additional address details that are sometimes needed for compliance, risk, or other scenarios where fine-grain address information might be needed. Not portable with common third party and open source. Redundant with core fields.<br/>For example, `address_portable.address_line_1` is usually a combination of `address_details.street_number`, `street_name`, and `street_type`.
 * @export
 * @interface AddressDetailsProperty
 */
export interface AddressDetailsProperty {
    /**
     * The street number.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'street_number'?: string;
    /**
     * The street name. Just `Drury` in `Drury Lane`.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'street_name'?: string;
    /**
     * The street type. For example, avenue, boulevard, road, or expressway.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'street_type'?: string;
    /**
     * The delivery service. Post office box, bag number, or post office name.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'delivery_service'?: string;
    /**
     * A named locations that represents the premise. Usually a building name or number or collection of buildings with a common name or number. For example, <code>Craven House</code>.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'building_name'?: string;
    /**
     * The first-order entity below a named building or location that represents the sub-premises. Usually a single building within a collection of buildings with a common name. Can be a flat, story, floor, room, or apartment.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'sub_building'?: string;
}

