/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AGREEMENTALREADYCANCELLED
 */
export interface AGREEMENTALREADYCANCELLED {
    /**
     * 
     * @type {string}
     * @memberof AGREEMENTALREADYCANCELLED
     */
    'description'?: AGREEMENTALREADYCANCELLEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof AGREEMENTALREADYCANCELLED
     */
    'issue'?: AGREEMENTALREADYCANCELLEDIssueEnum;
}

type AGREEMENTALREADYCANCELLEDDescriptionEnum = 'The requested agreement is already canceled.'
type AGREEMENTALREADYCANCELLEDIssueEnum = 'AGREEMENT_ALREADY_CANCELLED'


