/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ALIASDECLINEDBYPROCESSOR
 */
export interface ALIASDECLINEDBYPROCESSOR {
    /**
     * 
     * @type {string}
     * @memberof ALIASDECLINEDBYPROCESSOR
     */
    'description'?: ALIASDECLINEDBYPROCESSORDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ALIASDECLINEDBYPROCESSOR
     */
    'issue'?: ALIASDECLINEDBYPROCESSORIssueEnum;
}

type ALIASDECLINEDBYPROCESSORDescriptionEnum = 'The provided alias was declined by the processor. Please create a new order with a different alias_key and/or alias_label and try again.'
type ALIASDECLINEDBYPROCESSORIssueEnum = 'ALIAS_DECLINED_BY_PROCESSOR'


