/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';

/**
 * The breakdown of the amount. Breakdown provides details such as total item amount, total tax amount, shipping, handling, insurance, and discounts, if any.
 * @export
 * @interface AmountBreakdown
 */
export interface AmountBreakdown {
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'item_total'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'shipping'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'handling'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'tax_total'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'insurance'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'shipping_discount'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof AmountBreakdown
     */
    'discount'?: Money;
}

