/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AMOUNTNOTPATCHABLE
 */
export interface AMOUNTNOTPATCHABLE {
    /**
     * 
     * @type {string}
     * @memberof AMOUNTNOTPATCHABLE
     */
    'description'?: AMOUNTNOTPATCHABLEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof AMOUNTNOTPATCHABLE
     */
    'issue'?: AMOUNTNOTPATCHABLEIssueEnum;
}

type AMOUNTNOTPATCHABLEDescriptionEnum = 'The amount cannot be updated as the \'payer\' has chosen and approved a specific financing offer for a given amount. Please Create a new Order with the updated Order amount and have the \'payer\' approve the new payment terms.'
type AMOUNTNOTPATCHABLEIssueEnum = 'AMOUNT_NOT_PATCHABLE'


