/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AMOUNTCANNOTBESPECIFIED
 */
export interface AMOUNTCANNOTBESPECIFIED {
    /**
     * 
     * @type {string}
     * @memberof AMOUNTCANNOTBESPECIFIED
     */
    'description'?: AMOUNTCANNOTBESPECIFIEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof AMOUNTCANNOTBESPECIFIED
     */
    'issue'?: AMOUNTCANNOTBESPECIFIEDIssueEnum;
}

type AMOUNTCANNOTBESPECIFIEDDescriptionEnum = 'An authorization amount can only be specified if an Order has been saved by calling /v2/checkout/orders/{order_id}/save.  Please save the order and try again.'
type AMOUNTCANNOTBESPECIFIEDIssueEnum = 'AMOUNT_CANNOT_BE_SPECIFIED'


