/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AMOUNTCHANGENOTALLOWED
 */
export interface AMOUNTCHANGENOTALLOWED {
    /**
     * 
     * @type {string}
     * @memberof AMOUNTCHANGENOTALLOWED
     */
    'description'?: AMOUNTCHANGENOTALLOWEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof AMOUNTCHANGENOTALLOWED
     */
    'issue'?: AMOUNTCHANGENOTALLOWEDIssueEnum;
}

type AMOUNTCHANGENOTALLOWEDDescriptionEnum = 'The amount specified is different from the amount authorized by payer.'
type AMOUNTCHANGENOTALLOWEDIssueEnum = 'AMOUNT_CHANGE_NOT_ALLOWED'


