/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplePayPaymentData } from './apple-pay-payment-data';
import { Card } from './card';
import { Money2 } from './money2';

/**
 * Information about the Payment data obtained by decrypting Apple Pay token.
 * @export
 * @interface ApplePayDecryptedTokenData
 */
export interface ApplePayDecryptedTokenData {
    /**
     * 
     * @type {Money2}
     * @memberof ApplePayDecryptedTokenData
     */
    'transaction_amount'?: Money2;
    /**
     * 
     * @type {Card}
     * @memberof ApplePayDecryptedTokenData
     */
    'tokenized_card': Card;
    /**
     * Apple Pay Hex-encoded device manufacturer identifier. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ApplePayDecryptedTokenData
     */
    'device_manufacturer_id'?: string;
    /**
     * Indicates the type of payment data passed, in case of Non China the payment data is 3DSECURE and for China it is EMV.
     * @type {string}
     * @memberof ApplePayDecryptedTokenData
     */
    'payment_data_type'?: ApplePayDecryptedTokenDataPaymentDataTypeEnum;
    /**
     * 
     * @type {ApplePayPaymentData}
     * @memberof ApplePayDecryptedTokenData
     */
    'payment_data'?: ApplePayPaymentData;
}

type ApplePayDecryptedTokenDataPaymentDataTypeEnum = '3DSECURE' | 'EMV'


