/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the decrypted apple pay payment data for the token like cryptogram, eci indicator.
 * @export
 * @interface ApplePayPaymentData
 */
export interface ApplePayPaymentData {
    /**
     * Online payment cryptogram, as defined by 3D Secure. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ApplePayPaymentData
     */
    'cryptogram'?: string;
    /**
     * ECI indicator, as defined by 3- Secure. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ApplePayPaymentData
     */
    'eci_indicator'?: string;
    /**
     * Encoded Apple Pay EMV Payment Structure used for payments in China. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ApplePayPaymentData
     */
    'emv_data'?: string;
    /**
     * Bank Key encrypted Apple Pay PIN. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ApplePayPaymentData
     */
    'pin'?: string;
}

