/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplePayDecryptedTokenData } from './apple-pay-decrypted-token-data';
import { CardStoredCredential } from './card-stored-credential';
import { Phone } from './phone';

/**
 * Information needed to pay using ApplePay.
 * @export
 * @interface ApplePayRequest
 */
export interface ApplePayRequest {
    /**
     * ApplePay transaction identifier, this will be the unique identifier for this transaction provided by Apple. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ApplePayRequest
     */
    'id'?: string;
    /**
     * The full name representation like Mr J Smith.
     * @type {string}
     * @memberof ApplePayRequest
     */
    'name'?: string;
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof ApplePayRequest
     */
    'email_address'?: string;
    /**
     * 
     * @type {Phone}
     * @memberof ApplePayRequest
     */
    'phone_number'?: Phone;
    /**
     * 
     * @type {ApplePayDecryptedTokenData}
     * @memberof ApplePayRequest
     */
    'decrypted_token'?: ApplePayDecryptedTokenData;
    /**
     * 
     * @type {CardStoredCredential}
     * @memberof ApplePayRequest
     */
    'stored_credential'?: CardStoredCredential;
    /**
     * The PayPal-generated ID for the vaulted payment source. This ID should be stored on the merchant\'s server so the saved payment source can be used for future transactions.
     * @type {string}
     * @memberof ApplePayRequest
     */
    'vault_id'?: string;
    /**
     * 
     * @type {any}
     * @memberof ApplePayRequest
     */
    'attributes'?: any;
}

