/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthorizationStatusDetails } from './authorization-status-details';

/**
 * The status fields for an authorized payment.
 * @export
 * @interface AuthorizationStatus
 */
export interface AuthorizationStatus {
    /**
     * The status for the authorized payment.
     * @type {string}
     * @memberof AuthorizationStatus
     */
    'status'?: AuthorizationStatusStatusEnum;
    /**
     * 
     * @type {AuthorizationStatusDetails}
     * @memberof AuthorizationStatus
     */
    'status_details'?: AuthorizationStatusDetails;
}

type AuthorizationStatusStatusEnum = 'CREATED' | 'CAPTURED' | 'DENIED' | 'PARTIALLY_CAPTURED' | 'VOIDED' | 'PENDING'


