/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AUTHORIZATIONAMOUNTEXCEEDED
 */
export interface AUTHORIZATIONAMOUNTEXCEEDED {
    /**
     * 
     * @type {string}
     * @memberof AUTHORIZATIONAMOUNTEXCEEDED
     */
    'description'?: AUTHORIZATIONAMOUNTEXCEEDEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof AUTHORIZATIONAMOUNTEXCEEDED
     */
    'issue'?: AUTHORIZATIONAMOUNTEXCEEDEDIssueEnum;
}

type AUTHORIZATIONAMOUNTEXCEEDEDDescriptionEnum = 'Authorization amount specified exceeded allowable limit. Specify a different amount and try the request again. Alternately, contact Customer Support to increase your limits. Local regulations (e.g. in PSD2 countries) prohibit overages above the amount authorized by the payer.'
type AUTHORIZATIONAMOUNTEXCEEDEDIssueEnum = 'AUTHORIZATION_AMOUNT_EXCEEDED'


