/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProcessorResponse } from './processor-response';

/**
 * 
 * @export
 * @interface AuthorizationWithAdditionalDataAllOf
 */
export interface AuthorizationWithAdditionalDataAllOf {
    /**
     * 
     * @type {ProcessorResponse}
     * @memberof AuthorizationWithAdditionalDataAllOf
     */
    'processor_response'?: ProcessorResponse;
}

