/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LiabilityShift } from './liability-shift';
import { ThreeDSecureAuthenticationResponse } from './three-dsecure-authentication-response';

/**
 * Results of Authentication such as 3D Secure.
 * @export
 * @interface AuthenticationResponse
 */
export interface AuthenticationResponse {
    /**
     * Liability shift indicator. The outcome of the issuer\'s authentication.
     * @type {LiabilityShift}
     * @memberof AuthenticationResponse
     */
    'liability_shift'?: LiabilityShift;
    /**
     * 
     * @type {ThreeDSecureAuthenticationResponse}
     * @memberof AuthenticationResponse
     */
    'three_d_secure'?: ThreeDSecureAuthenticationResponse;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationResponse
     */
    'authentication_flow'?: any;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationResponse
     */
    'exemption_details'?: any;
}

