/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityTimestamps } from './activity-timestamps';
import { AuthorizationAllOf } from './authorization-all-of';
import { AuthorizationStatus } from './authorization-status';
import { AuthorizationStatusDetails } from './authorization-status-details';
import { LinkDescription } from './link-description';
import { Money } from './money';
import { NetworkTransactionReference } from './network-transaction-reference';
import { SellerProtection } from './seller-protection';

/**
 * @type Authorization
 * The authorized payment transaction.
 * @export
 */
export type Authorization = ActivityTimestamps & AuthorizationAllOf & AuthorizationStatus;


