/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Authorization } from './authorization';
import { AuthorizationStatusDetails } from './authorization-status-details';
import { AuthorizationWithAdditionalDataAllOf } from './authorization-with-additional-data-all-of';
import { LinkDescription } from './link-description';
import { Money } from './money';
import { NetworkTransactionReference } from './network-transaction-reference';
import { ProcessorResponse } from './processor-response';
import { SellerProtection } from './seller-protection';

/**
 * @type AuthorizationWithAdditionalData
 * The authorization with additional payment details, such as risk assessment and processor response. These details are populated only for certain payment methods.
 * @export
 */
export type AuthorizationWithAdditionalData = Authorization & AuthorizationWithAdditionalDataAllOf;


