/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BANKNOTSUPPORTEDFORVERIFICATION
 */
export interface BANKNOTSUPPORTEDFORVERIFICATION {
    /**
     * 
     * @type {string}
     * @memberof BANKNOTSUPPORTEDFORVERIFICATION
     */
    'description'?: BANKNOTSUPPORTEDFORVERIFICATIONDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof BANKNOTSUPPORTEDFORVERIFICATION
     */
    'issue'?: BANKNOTSUPPORTEDFORVERIFICATIONIssueEnum;
}

type BANKNOTSUPPORTEDFORVERIFICATIONDescriptionEnum = 'Verification for this bank account is not supported.'
type BANKNOTSUPPORTEDFORVERIFICATIONIssueEnum = 'BANK_NOT_SUPPORTED_FOR_VERIFICATION'


