/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BILLINGAGREEMENTNOTFOUND
 */
export interface BILLINGAGREEMENTNOTFOUND {
    /**
     * 
     * @type {string}
     * @memberof BILLINGAGREEMENTNOTFOUND
     */
    'description'?: BILLINGAGREEMENTNOTFOUNDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof BILLINGAGREEMENTNOTFOUND
     */
    'issue'?: BILLINGAGREEMENTNOTFOUNDIssueEnum;
}

type BILLINGAGREEMENTNOTFOUNDDescriptionEnum = 'The requested Billing Agreement token was not found.'
type BILLINGAGREEMENTNOTFOUNDIssueEnum = 'BILLING_AGREEMENT_NOT_FOUND'


