/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BILLINGAGREEMENTIDMISMATCH
 */
export interface BILLINGAGREEMENTIDMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof BILLINGAGREEMENTIDMISMATCH
     */
    'description'?: BILLINGAGREEMENTIDMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof BILLINGAGREEMENTIDMISMATCH
     */
    'issue'?: BILLINGAGREEMENTIDMISMATCHIssueEnum;
}

type BILLINGAGREEMENTIDMISMATCHDescriptionEnum = 'Billing Agreement ID must exactly match the Billing Agreement ID that was provided during order creation.'
type BILLINGAGREEMENTIDMISMATCHIssueEnum = 'BILLING_AGREEMENT_ID_MISMATCH'


