/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BILLINGADDRESSINVALID
 */
export interface BILLINGADDRESSINVALID {
    /**
     * 
     * @type {string}
     * @memberof BILLINGADDRESSINVALID
     */
    'description'?: BILLINGADDRESSINVALIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof BILLINGADDRESSINVALID
     */
    'issue'?: BILLINGADDRESSINVALIDIssueEnum;
}

type BILLINGADDRESSINVALIDDescriptionEnum = 'Provided billing address is invalid.'
type BILLINGADDRESSINVALIDIssueEnum = 'BILLING_ADDRESS_INVALID'


