/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Bank Identification Number (BIN) details used to fund a payment.
 * @export
 * @interface BinDetails
 */
export interface BinDetails {
    /**
     * The Bank Identification Number (BIN) signifies the number that is being used to identify the granular level details (except the PII information) of the card.
     * @type {string}
     * @memberof BinDetails
     */
    'bin'?: string;
    /**
     * The issuer of the card instrument.
     * @type {string}
     * @memberof BinDetails
     */
    'issuing_bank'?: string;
    /**
     * The [two-character ISO 3166-1 code](https://raw.githubusercontent.com) that identifies the country or region.<blockquote><strong>Note:</strong> The country code for Great Britain is <code>GB</code> and not <code>UK</code> as used in the top-level domain names for that country. Use the `C2` country code for China worldwide for comparable uncontrolled price (CUP) method, bank card, and cross-border transactions.</blockquote>
     * @type {string}
     * @memberof BinDetails
     */
    'bin_country_code'?: string;
    /**
     * The type of card product assigned to the BIN by the issuer. These values are defined by the issuer and may change over time. Some examples include: PREPAID_GIFT, CONSUMER, CORPORATE.
     * @type {Array<string>}
     * @memberof BinDetails
     */
    'products'?: Array<string>;
}

