/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BlikExperienceContextAllOf
 */
export interface BlikExperienceContextAllOf {
    /**
     * An Internet Protocol address (IP address). This address assigns a numerical label to each device that is connected to a computer network through the Internet Protocol. Supports IPv4 and IPv6 addresses.
     * @type {string}
     * @memberof BlikExperienceContextAllOf
     */
    'consumer_ip'?: string;
    /**
     * The payer\'s User Agent. For example, Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0).
     * @type {string}
     * @memberof BlikExperienceContextAllOf
     */
    'consumer_user_agent'?: string;
}

