/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BLIKONECLICKMISSINGREQUIREDPARAMETER
 */
export interface BLIKONECLICKMISSINGREQUIREDPARAMETER {
    /**
     * 
     * @type {string}
     * @memberof BLIKONECLICKMISSINGREQUIREDPARAMETER
     */
    'description'?: BLIKONECLICKMISSINGREQUIREDPARAMETERDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof BLIKONECLICKMISSINGREQUIREDPARAMETER
     */
    'issue'?: BLIKONECLICKMISSINGREQUIREDPARAMETERIssueEnum;
}

type BLIKONECLICKMISSINGREQUIREDPARAMETERDescriptionEnum = 'Blik\'s one_click flow requires one_click.auth_code and one_click.alias_label parameters for the buyer\'s first transaction. For all subsequent transactions,only the one_click.alias_key parameter is required.'
type BLIKONECLICKMISSINGREQUIREDPARAMETERIssueEnum = 'BLIK_ONE_CLICK_MISSING_REQUIRED_PARAMETER'


