/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CANCELURLREQUIRED
 */
export interface CANCELURLREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof CANCELURLREQUIRED
     */
    'description'?: CANCELURLREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CANCELURLREQUIRED
     */
    'issue'?: CANCELURLREQUIREDIssueEnum;
}

type CANCELURLREQUIREDDescriptionEnum = 'The cancel url is required when attempting to vault this source.'
type CANCELURLREQUIREDIssueEnum = 'CANCEL_URL_REQUIRED'


