/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CANNOTBEZEROORNEGATIVE
 */
export interface CANNOTBEZEROORNEGATIVE {
    /**
     * 
     * @type {string}
     * @memberof CANNOTBEZEROORNEGATIVE
     */
    'description'?: CANNOTBEZEROORNEGATIVEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CANNOTBEZEROORNEGATIVE
     */
    'issue'?: CANNOTBEZEROORNEGATIVEIssueEnum;
}

type CANNOTBEZEROORNEGATIVEDescriptionEnum = 'Must be greater than zero. If the currency supports decimals, only two decimal place precision is supported.'
type CANNOTBEZEROORNEGATIVEIssueEnum = 'CANNOT_BE_ZERO_OR_NEGATIVE'


