/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CAPTURESTATUSNOTVALID
 */
export interface CAPTURESTATUSNOTVALID {
    /**
     * 
     * @type {string}
     * @memberof CAPTURESTATUSNOTVALID
     */
    'description'?: CAPTURESTATUSNOTVALIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CAPTURESTATUSNOTVALID
     */
    'issue'?: CAPTURESTATUSNOTVALIDIssueEnum;
}

type CAPTURESTATUSNOTVALIDDescriptionEnum = 'Invalid capture status. Tracker information can only be added to captures in `COMPLETED` state.'
type CAPTURESTATUSNOTVALIDIssueEnum = 'CAPTURE_STATUS_NOT_VALID'


