/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The details of the captured payment status.
 * @export
 * @interface CaptureStatusDetails
 */
export interface CaptureStatusDetails {
    /**
     * The reason why the captured payment status is `PENDING` or `DENIED`.
     * @type {string}
     * @memberof CaptureStatusDetails
     */
    'reason'?: CaptureStatusDetailsReasonEnum;
}

type CaptureStatusDetailsReasonEnum = 'BUYER_COMPLAINT' | 'CHARGEBACK' | 'ECHECK' | 'INTERNATIONAL_WITHDRAWAL' | 'OTHER' | 'PENDING_REVIEW' | 'RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION' | 'REFUNDED' | 'TRANSACTION_APPROVED_AWAITING_FUNDING' | 'UNILATERAL' | 'VERIFICATION_REQUIRED'


