/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CAPTUREIDNOTFOUND
 */
export interface CAPTUREIDNOTFOUND {
    /**
     * 
     * @type {string}
     * @memberof CAPTUREIDNOTFOUND
     */
    'description'?: CAPTUREIDNOTFOUNDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CAPTUREIDNOTFOUND
     */
    'issue'?: CAPTUREIDNOTFOUNDIssueEnum;
}

type CAPTUREIDNOTFOUNDDescriptionEnum = 'Specified capture ID does not exist. Check the capture ID and try again.'
type CAPTUREIDNOTFOUNDIssueEnum = 'CAPTURE_ID_NOT_FOUND'


