/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardExperienceContext } from './card-experience-context';
import { CardStoredCredential } from './card-stored-credential';
import { NetworkTokenRequest } from './network-token-request';

/**
 * 
 * @export
 * @interface CardRequestAllOf
 */
export interface CardRequestAllOf {
    /**
     * The PayPal-generated ID for the vaulted payment source. This ID should be stored on the merchant\'s server so the saved payment source can be used for future transactions.
     * @type {string}
     * @memberof CardRequestAllOf
     */
    'vault_id'?: string;
    /**
     * 
     * @type {CardStoredCredential}
     * @memberof CardRequestAllOf
     */
    'stored_credential'?: CardStoredCredential;
    /**
     * 
     * @type {NetworkTokenRequest}
     * @memberof CardRequestAllOf
     */
    'network_token'?: NetworkTokenRequest;
    /**
     * 
     * @type {CardExperienceContext}
     * @memberof CardRequestAllOf
     */
    'experience_context'?: CardExperienceContext;
}

