/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CARDEXPIRYREQUIRED
 */
export interface CARDEXPIRYREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof CARDEXPIRYREQUIRED
     */
    'description'?: CARDEXPIRYREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CARDEXPIRYREQUIRED
     */
    'issue'?: CARDEXPIRYREQUIREDIssueEnum;
}

type CARDEXPIRYREQUIREDDescriptionEnum = 'The card expiry is required when attempting to process payment with card.'
type CARDEXPIRYREQUIREDIssueEnum = 'CARD_EXPIRY_REQUIRED'


