/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Representation of card details as received in the request.
 * @export
 * @interface CardFromRequest
 */
export interface CardFromRequest {
    /**
     * The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof CardFromRequest
     */
    'expiry'?: string;
    /**
     * The last digits of the payment card.
     * @type {string}
     * @memberof CardFromRequest
     */
    'last_digits'?: string;
}

