/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Level2CardProcessingData } from './level2-card-processing-data';
import { Level3CardProcessingData } from './level3-card-processing-data';

/**
 * Merchants and partners can add Level 2 and 3 data to payments to reduce risk and payment processing costs. For more information about processing payments, see <a href=\"https://developer.paypal.com/docs/checkout/advanced/processing/\">checkout</a> or <a href=\"https://developer.paypal.com/docs/multiparty/checkout/advanced/processing/\">multiparty checkout</a>.
 * @export
 * @interface CardSupplementaryData
 */
export interface CardSupplementaryData {
    /**
     * 
     * @type {Level2CardProcessingData}
     * @memberof CardSupplementaryData
     */
    'level_2'?: Level2CardProcessingData;
    /**
     * 
     * @type {Level3CardProcessingData}
     * @memberof CardSupplementaryData
     */
    'level_3'?: Level3CardProcessingData;
}

