/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CARDTYPENOTSUPPORTED
 */
export interface CARDTYPENOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof CARDTYPENOTSUPPORTED
     */
    'description'?: CARDTYPENOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CARDTYPENOTSUPPORTED
     */
    'issue'?: CARDTYPENOTSUPPORTEDIssueEnum;
}

type CARDTYPENOTSUPPORTEDDescriptionEnum = 'Processing of this card type is not supported. Use another card type.'
type CARDTYPENOTSUPPORTEDIssueEnum = 'CARD_TYPE_NOT_SUPPORTED'


