/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Customer } from './customer';
import { VaultInstructionBase } from './vault-instruction-base';

/**
 * Additional attributes associated with the use of this card.
 * @export
 * @interface CardAttributes
 */
export interface CardAttributes {
    /**
     * 
     * @type {Customer}
     * @memberof CardAttributes
     */
    'customer'?: Customer;
    /**
     * 
     * @type {VaultInstructionBase}
     * @memberof CardAttributes
     */
    'vault'?: VaultInstructionBase;
}

