/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticationResponse } from './authentication-response';
import { BinDetails } from './bin-details';
import { CardAttributesResponse } from './card-attributes-response';
import { CardBrand } from './card-brand';
import { CardFromRequest } from './card-from-request';

/**
 * The payment card to use to fund a payment. Card can be a credit or debit card.
 * @export
 * @interface CardResponse
 */
export interface CardResponse {
    /**
     * The card holder\'s name as it appears on the card.
     * @type {string}
     * @memberof CardResponse
     */
    'name'?: string;
    /**
     * The last digits of the payment card.
     * @type {string}
     * @memberof CardResponse
     */
    'last_digits'?: string;
    /**
     * The card network or brand. Applies to credit, debit, gift, and payment cards.
     * @type {CardBrand}
     * @memberof CardResponse
     */
    'brand'?: CardBrand;
    /**
     * Array of brands or networks associated with the card.
     * @type {Array<CardBrand>}
     * @memberof CardResponse
     */
    'available_networks'?: Array<CardBrand>;
    /**
     * The payment card type.
     * @type {string}
     * @memberof CardResponse
     */
    'type'?: CardResponseTypeEnum;
    /**
     * 
     * @type {AuthenticationResponse}
     * @memberof CardResponse
     */
    'authentication_result'?: AuthenticationResponse;
    /**
     * 
     * @type {CardAttributesResponse}
     * @memberof CardResponse
     */
    'attributes'?: CardAttributesResponse;
    /**
     * 
     * @type {CardFromRequest}
     * @memberof CardResponse
     */
    'from_request'?: CardFromRequest;
    /**
     * The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof CardResponse
     */
    'expiry'?: string;
    /**
     * 
     * @type {BinDetails}
     * @memberof CardResponse
     */
    'bin_details'?: BinDetails;
}

type CardResponseTypeEnum = 'CREDIT' | 'DEBIT' | 'PREPAID' | 'UNKNOWN'


