/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The intent to either capture payment immediately or authorize a payment for an order after order creation.
 * @export
 * @enum {string}
 */
export type CheckoutPaymentIntent = 'CAPTURE' | 'AUTHORIZE'

