/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { PayeeBase } from './payee-base';

/**
 * Details about the merchant cobranded card used for order purchase.
 * @export
 * @interface CobrandedCard
 */
export interface CobrandedCard {
    /**
     * Array of labels for the cobranded card.
     * @type {Array<string>}
     * @memberof CobrandedCard
     */
    'labels'?: Array<string>;
    /**
     * 
     * @type {PayeeBase}
     * @memberof CobrandedCard
     */
    'payee'?: PayeeBase;
    /**
     * 
     * @type {Money}
     * @memberof CobrandedCard
     */
    'amount'?: Money;
}

