/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface COMPLIANCEVIOLATION
 */
export interface COMPLIANCEVIOLATION {
    /**
     * 
     * @type {string}
     * @memberof COMPLIANCEVIOLATION
     */
    'description'?: COMPLIANCEVIOLATIONDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof COMPLIANCEVIOLATION
     */
    'issue'?: COMPLIANCEVIOLATIONIssueEnum;
}

type COMPLIANCEVIOLATIONDescriptionEnum = 'Transaction is declined due to compliance violation.'
type COMPLIANCEVIOLATIONIssueEnum = 'COMPLIANCE_VIOLATION'


