/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CURRENCYNOTSUPPORTEDFORCARDTYPE
 */
export interface CURRENCYNOTSUPPORTEDFORCARDTYPE {
    /**
     * 
     * @type {string}
     * @memberof CURRENCYNOTSUPPORTEDFORCARDTYPE
     */
    'description'?: CURRENCYNOTSUPPORTEDFORCARDTYPEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CURRENCYNOTSUPPORTEDFORCARDTYPE
     */
    'issue'?: CURRENCYNOTSUPPORTEDFORCARDTYPEIssueEnum;
}

type CURRENCYNOTSUPPORTEDFORCARDTYPEDescriptionEnum = 'The issued currency code of this card is not supported for direct card payments. Please refer https://developer.paypal.com/api/rest/reference/currency-codes/ for list of supported currency codes.'
type CURRENCYNOTSUPPORTEDFORCARDTYPEIssueEnum = 'CURRENCY_NOT_SUPPORTED_FOR_CARD_TYPE'


