/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CURRENCYNOTSUPPORTEDFORCOUNTRY
 */
export interface CURRENCYNOTSUPPORTEDFORCOUNTRY {
    /**
     * 
     * @type {string}
     * @memberof CURRENCYNOTSUPPORTEDFORCOUNTRY
     */
    'description'?: CURRENCYNOTSUPPORTEDFORCOUNTRYDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CURRENCYNOTSUPPORTEDFORCOUNTRY
     */
    'issue'?: CURRENCYNOTSUPPORTEDFORCOUNTRYIssueEnum;
}

type CURRENCYNOTSUPPORTEDFORCOUNTRYDescriptionEnum = ' For the payment_source specified, the currency of the Order is restricted by the country in which the payee account is based. Please refer https://developer.paypal.com/api/rest/reference/currency-codes/ for list of supported currency codes.'
type CURRENCYNOTSUPPORTEDFORCOUNTRYIssueEnum = 'CURRENCY_NOT_SUPPORTED_FOR_COUNTRY'


