/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CURRENCYNOTSUPPORTEDFORBANK
 */
export interface CURRENCYNOTSUPPORTEDFORBANK {
    /**
     * 
     * @type {string}
     * @memberof CURRENCYNOTSUPPORTEDFORBANK
     */
    'description'?: CURRENCYNOTSUPPORTEDFORBANKDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof CURRENCYNOTSUPPORTEDFORBANK
     */
    'issue'?: CURRENCYNOTSUPPORTEDFORBANKIssueEnum;
}

type CURRENCYNOTSUPPORTEDFORBANKDescriptionEnum = 'The payment_source does not support the currency of the Order. For ACH debit, only USD is supported and for SEPA debit, only EUR is supported.'
type CURRENCYNOTSUPPORTEDFORBANKIssueEnum = 'CURRENCY_NOT_SUPPORTED_FOR_BANK'


