/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneWithType } from './phone-with-type';

/**
 * The details about a customer in PayPal\'s system of record.
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * The unique ID for a customer generated by PayPal.
     * @type {string}
     * @memberof Customer
     */
    'id'?: string;
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof Customer
     */
    'email_address'?: string;
    /**
     * 
     * @type {PhoneWithType}
     * @memberof Customer
     */
    'phone'?: PhoneWithType;
}

