/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DECIMALPRECISION
 */
export interface DECIMALPRECISION {
    /**
     * 
     * @type {string}
     * @memberof DECIMALPRECISION
     */
    'description'?: DECIMALPRECISIONDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof DECIMALPRECISION
     */
    'issue'?: DECIMALPRECISIONIssueEnum;
}

type DECIMALPRECISIONDescriptionEnum = 'If the currency supports decimals, only two decimal place precision is supported.'
type DECIMALPRECISIONIssueEnum = 'DECIMAL_PRECISION'


