/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DEVICEDATANOTAVAILABLE
 */
export interface DEVICEDATANOTAVAILABLE {
    /**
     * 
     * @type {string}
     * @memberof DEVICEDATANOTAVAILABLE
     */
    'description'?: DEVICEDATANOTAVAILABLEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof DEVICEDATANOTAVAILABLE
     */
    'issue'?: DEVICEDATANOTAVAILABLEIssueEnum;
}

type DEVICEDATANOTAVAILABLEDescriptionEnum = 'Device Data is not available for processing this order. The PayPal-Client-Metadata-Id header value sent during `Create Order` api call is either missing or incorrect or there was an error in collecting required data. Please verify if appropriate value for PayPal-Client-Metadata-Id header is being sent during \'Create Order\' api call. Please note this error only applies to payment_source.pay_upon_invoice at the moment.'
type DEVICEDATANOTAVAILABLEIssueEnum = 'DEVICE_DATA_NOT_AVAILABLE'


