/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DOMESTICTRANSACTIONREQUIRED
 */
export interface DOMESTICTRANSACTIONREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof DOMESTICTRANSACTIONREQUIRED
     */
    'description'?: DOMESTICTRANSACTIONREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof DOMESTICTRANSACTIONREQUIRED
     */
    'issue'?: DOMESTICTRANSACTIONREQUIREDIssueEnum;
}

type DOMESTICTRANSACTIONREQUIREDDescriptionEnum = 'This transaction requires the payee and payer to be resident in the same country, a domestic transaction is required to create this payment.'
type DOMESTICTRANSACTIONREQUIREDIssueEnum = 'DOMESTIC_TRANSACTION_REQUIRED'


