/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DONATIONITEMSNOTSUPPORTED
 */
export interface DONATIONITEMSNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof DONATIONITEMSNOTSUPPORTED
     */
    'description'?: DONATIONITEMSNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof DONATIONITEMSNOTSUPPORTED
     */
    'issue'?: DONATIONITEMSNOTSUPPORTEDIssueEnum;
}

type DONATIONITEMSNOTSUPPORTEDDescriptionEnum = 'If \'purchase_unit\' has \"DONATION\" as the \'items.category\' then the Order can at most have one purchase_unit. Multiple purchase_units are not supported if either of them have at least one items with category as \"DONATION\".'
type DONATIONITEMSNOTSUPPORTEDIssueEnum = 'DONATION_ITEMS_NOT_SUPPORTED'


