/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DUPLICATEREFERENCEID
 */
export interface DUPLICATEREFERENCEID {
    /**
     * 
     * @type {string}
     * @memberof DUPLICATEREFERENCEID
     */
    'description'?: DUPLICATEREFERENCEIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof DUPLICATEREFERENCEID
     */
    'issue'?: DUPLICATEREFERENCEIDIssueEnum;
}

type DUPLICATEREFERENCEIDDescriptionEnum = '`reference_id` must be unique if multiple `purchase_unit` are provided.'
type DUPLICATEREFERENCEIDIssueEnum = 'DUPLICATE_REFERENCE_ID'


