/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Electronic Commerce Indicator (ECI). The ECI value is part of the 2 data elements that indicate the transaction was processed electronically. This should be passed on the authorization transaction to the Gateway/Processor.
 * @export
 * @enum {string}
 */
export type EciFlag = 'MASTERCARD_NON_3D_SECURE_TRANSACTION' | 'MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION' | 'MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION' | 'FULLY_AUTHENTICATED_TRANSACTION' | 'ATTEMPTED_AUTHENTICATION_TRANSACTION' | 'NON_3D_SECURE_TRANSACTION'

