/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error400 } from './error400';
import { Error401 } from './error401';
import { Error403 } from './error403';
import { Error404 } from './error404';
import { Error409 } from './error409';
import { Error415 } from './error415';
import { Error422 } from './error422';
import { Error500 } from './error500';
import { Error503 } from './error503';
import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * @type ErrorDefault
 * The default error response.
 * @export
 */
export type ErrorDefault = Error400 | Error401 | Error403 | Error404 | Error409 | Error415 | Error422 | Error500 | Error503;


