/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * Request is not well-formed, syntactically incorrect, or violates schema.
 * @export
 * @interface Error400
 */
export interface Error400 {
    /**
     * 
     * @type {string}
     * @memberof Error400
     */
    'name'?: Error400NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error400
     */
    'message'?: Error400MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error400
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error400
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error400
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error400NameEnum = 'INVALID_REQUEST'
type Error400MessageEnum = 'Request is not well-formed, syntactically incorrect, or violates schema.'


