/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information.
 * @export
 * @interface ErrorLinkDescription
 */
export interface ErrorLinkDescription {
    /**
     * The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call.
     * @type {string}
     * @memberof ErrorLinkDescription
     */
    'href': string;
    /**
     * The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
     * @type {string}
     * @memberof ErrorLinkDescription
     */
    'rel': string;
    /**
     * The HTTP method required to make the related call.
     * @type {string}
     * @memberof ErrorLinkDescription
     */
    'method'?: ErrorLinkDescriptionMethodEnum;
}

type ErrorLinkDescriptionMethodEnum = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'


