/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The exchange rate that determines the amount to convert from one currency to another currency.
 * @export
 * @interface ExchangeRate
 */
export interface ExchangeRate {
    /**
     * The [three-character ISO-4217 currency code](https://raw.githubusercontent.com) that identifies the currency.
     * @type {string}
     * @memberof ExchangeRate
     */
    'source_currency'?: string;
    /**
     * The [three-character ISO-4217 currency code](https://raw.githubusercontent.com) that identifies the currency.
     * @type {string}
     * @memberof ExchangeRate
     */
    'target_currency'?: string;
    /**
     * The target currency amount. Equivalent to one unit of the source currency. Formatted as integer or decimal value with one to 15 digits to the right of the decimal point.
     * @type {string}
     * @memberof ExchangeRate
     */
    'value'?: string;
}

