/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Customizes the payer experience during the approval process for the payment.
 * @export
 * @interface ExperienceContextBase
 */
export interface ExperienceContextBase {
    /**
     * The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof ExperienceContextBase
     */
    'brand_name'?: string;
    /**
     * The [language tag](https://tools.ietf.org/html/bcp47#section-2) for the language in which to localize the error-related strings, such as messages, issues, and suggested actions. The tag is made up of the [ISO 639-2 language code](https://www.loc.gov/standards/iso639-2/php/code_list.php), the optional [ISO-15924 script tag](https://www.unicode.org/iso15924/codelists.html), and the [ISO-3166 alpha-2 country code](https://raw.githubusercontent.com) or [M49 region code](https://unstats.un.org/unsd/methodology/m49/).
     * @type {string}
     * @memberof ExperienceContextBase
     */
    'locale'?: string;
    /**
     * The location from which the shipping address is derived.
     * @type {string}
     * @memberof ExperienceContextBase
     */
    'shipping_preference'?: ExperienceContextBaseShippingPreferenceEnum;
    /**
     * Describes the URL.
     * @type {string}
     * @memberof ExperienceContextBase
     */
    'return_url'?: string;
    /**
     * Describes the URL.
     * @type {string}
     * @memberof ExperienceContextBase
     */
    'cancel_url'?: string;
}

type ExperienceContextBaseShippingPreferenceEnum = 'GET_FROM_FILE' | 'NO_SHIPPING' | 'SET_PROVIDED_ADDRESS'


