/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FIELDNOTPATCHABLE
 */
export interface FIELDNOTPATCHABLE {
    /**
     * 
     * @type {string}
     * @memberof FIELDNOTPATCHABLE
     */
    'description'?: FIELDNOTPATCHABLEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof FIELDNOTPATCHABLE
     */
    'issue'?: FIELDNOTPATCHABLEIssueEnum;
}

type FIELDNOTPATCHABLEDescriptionEnum = 'Field cannot be patched.'
type FIELDNOTPATCHABLEIssueEnum = 'FIELD_NOT_PATCHABLE'


