/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GOOGLEPAYGATEWAYMERCHANTIDMISMATCH
 */
export interface GOOGLEPAYGATEWAYMERCHANTIDMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof GOOGLEPAYGATEWAYMERCHANTIDMISMATCH
     */
    'description'?: GOOGLEPAYGATEWAYMERCHANTIDMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof GOOGLEPAYGATEWAYMERCHANTIDMISMATCH
     */
    'issue'?: GOOGLEPAYGATEWAYMERCHANTIDMISMATCHIssueEnum;
}

type GOOGLEPAYGATEWAYMERCHANTIDMISMATCHDescriptionEnum = 'The gateway merchant ID in Google Pay token is not valid. This could be because the gateway merchant Id that was authorized by payer/buyer on Google Pay does not match with the API caller of the order.'
type GOOGLEPAYGATEWAYMERCHANTIDMISMATCHIssueEnum = 'GOOGLE_PAY_GATEWAY_MERCHANT_ID_MISMATCH'


