/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IBANCOUNTRYNOTSUPPORTED
 */
export interface IBANCOUNTRYNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof IBANCOUNTRYNOTSUPPORTED
     */
    'description'?: IBANCOUNTRYNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof IBANCOUNTRYNOTSUPPORTED
     */
    'issue'?: IBANCOUNTRYNOTSUPPORTEDIssueEnum;
}

type IBANCOUNTRYNOTSUPPORTEDDescriptionEnum = 'Country code of issuer bank for the provided IBAN is not supported for SEPA debit payments.'
type IBANCOUNTRYNOTSUPPORTEDIssueEnum = 'IBAN_COUNTRY_NOT_SUPPORTED'


