/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IDENTIFIERNOTFOUND
 */
export interface IDENTIFIERNOTFOUND {
    /**
     * 
     * @type {string}
     * @memberof IDENTIFIERNOTFOUND
     */
    'description'?: IDENTIFIERNOTFOUNDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof IDENTIFIERNOTFOUND
     */
    'issue'?: IDENTIFIERNOTFOUNDIssueEnum;
}

type IDENTIFIERNOTFOUNDDescriptionEnum = 'Specified identifier was not found. Please verify the correct identifier was used and try the request again.'
type IDENTIFIERNOTFOUNDIssueEnum = 'IDENTIFIER_NOT_FOUND'


