/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INCOMPATIBLEPARAMETERVALUE
 */
export interface INCOMPATIBLEPARAMETERVALUE {
    /**
     * 
     * @type {string}
     * @memberof INCOMPATIBLEPARAMETERVALUE
     */
    'description'?: INCOMPATIBLEPARAMETERVALUEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INCOMPATIBLEPARAMETERVALUE
     */
    'issue'?: INCOMPATIBLEPARAMETERVALUEIssueEnum;
}

type INCOMPATIBLEPARAMETERVALUEDescriptionEnum = 'The value of the field is incompatible/redundant with other fields in the order.'
type INCOMPATIBLEPARAMETERVALUEIssueEnum = 'INCOMPATIBLE_PARAMETER_VALUE'


