/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INSTRUMENTDECLINED
 */
export interface INSTRUMENTDECLINED {
    /**
     * 
     * @type {string}
     * @memberof INSTRUMENTDECLINED
     */
    'description'?: INSTRUMENTDECLINEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INSTRUMENTDECLINED
     */
    'issue'?: INSTRUMENTDECLINEDIssueEnum;
}

type INSTRUMENTDECLINEDDescriptionEnum = 'The instrument presented  was either declined by the processor or bank, or it can\'t be used for this payment.'
type INSTRUMENTDECLINEDIssueEnum = 'INSTRUMENT_DECLINED'


