/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPAYERID
 */
export interface INVALIDPAYERID {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPAYERID
     */
    'description'?: INVALIDPAYERIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPAYERID
     */
    'issue'?: INVALIDPAYERIDIssueEnum;
}

type INVALIDPAYERIDDescriptionEnum = 'The payer ID is not valid.'
type INVALIDPAYERIDIssueEnum = 'INVALID_PAYER_ID'


