/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPAYEEPRICINGTIERID
 */
export interface INVALIDPAYEEPRICINGTIERID {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPAYEEPRICINGTIERID
     */
    'description'?: INVALIDPAYEEPRICINGTIERIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPAYEEPRICINGTIERID
     */
    'issue'?: INVALIDPAYEEPRICINGTIERIDIssueEnum;
}

type INVALIDPAYEEPRICINGTIERIDDescriptionEnum = 'Please check the value specified or confirm with your Account Manager that the \'payee_pricing_tier_id\' specified has been setup for the account.'
type INVALIDPAYEEPRICINGTIERIDIssueEnum = 'INVALID_PAYEE_PRICING_TIER_ID'


