/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDCOUNTRYCODE
 */
export interface INVALIDCOUNTRYCODE {
    /**
     * 
     * @type {string}
     * @memberof INVALIDCOUNTRYCODE
     */
    'description'?: INVALIDCOUNTRYCODEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDCOUNTRYCODE
     */
    'issue'?: INVALIDCOUNTRYCODEIssueEnum;
}

type INVALIDCOUNTRYCODEDescriptionEnum = 'Country code is invalid. Please refer to https://developer.paypal.com/api/rest/reference/country-codes/ for a list of supported country codes.'
type INVALIDCOUNTRYCODEIssueEnum = 'INVALID_COUNTRY_CODE'


