/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDJSONPOINTERFORMAT1
 */
export interface INVALIDJSONPOINTERFORMAT1 {
    /**
     * 
     * @type {string}
     * @memberof INVALIDJSONPOINTERFORMAT1
     */
    'description'?: INVALIDJSONPOINTERFORMAT1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDJSONPOINTERFORMAT1
     */
    'issue'?: INVALIDJSONPOINTERFORMAT1IssueEnum;
}

type INVALIDJSONPOINTERFORMAT1DescriptionEnum = 'Path should be a valid [JSON Pointer](https://tools.ietf.org/html/rfc6901) that references a location within the request where the operation is performed.'
type INVALIDJSONPOINTERFORMAT1IssueEnum = 'INVALID_JSON_POINTER_FORMAT'


