/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDACCOUNTSTATUS
 */
export interface INVALIDACCOUNTSTATUS {
    /**
     * 
     * @type {string}
     * @memberof INVALIDACCOUNTSTATUS
     */
    'description'?: INVALIDACCOUNTSTATUSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDACCOUNTSTATUS
     */
    'issue'?: INVALIDACCOUNTSTATUSIssueEnum;
}

type INVALIDACCOUNTSTATUSDescriptionEnum = 'Account validations failed for the user.'
type INVALIDACCOUNTSTATUSIssueEnum = 'INVALID_ACCOUNT_STATUS'


