/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDFXRATEID
 */
export interface INVALIDFXRATEID {
    /**
     * 
     * @type {string}
     * @memberof INVALIDFXRATEID
     */
    'description'?: INVALIDFXRATEIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDFXRATEID
     */
    'issue'?: INVALIDFXRATEIDIssueEnum;
}

type INVALIDFXRATEIDDescriptionEnum = 'The specific FX Rate ID is not valid. This could be either because we are not able to look up the FX Rate based on this ID or it could be because the ID belongs to another API Caller.'
type INVALIDFXRATEIDIssueEnum = 'INVALID_FX_RATE_ID'


