/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPARAMETERVALUE
 */
export interface INVALIDPARAMETERVALUE {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETERVALUE
     */
    'description'?: INVALIDPARAMETERVALUEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETERVALUE
     */
    'issue'?: INVALIDPARAMETERVALUEIssueEnum;
}

type INVALIDPARAMETERVALUEDescriptionEnum = 'A parameter value is not valid.'
type INVALIDPARAMETERVALUEIssueEnum = 'INVALID_PARAMETER_VALUE'


