/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPARAMETERVALUE1
 */
export interface INVALIDPARAMETERVALUE1 {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETERVALUE1
     */
    'description'?: INVALIDPARAMETERVALUE1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETERVALUE1
     */
    'issue'?: INVALIDPARAMETERVALUE1IssueEnum;
}

type INVALIDPARAMETERVALUE1DescriptionEnum = 'The value of a field is invalid.'
type INVALIDPARAMETERVALUE1IssueEnum = 'INVALID_PARAMETER_VALUE'


