/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDSECURITYCODELENGTH
 */
export interface INVALIDSECURITYCODELENGTH {
    /**
     * 
     * @type {string}
     * @memberof INVALIDSECURITYCODELENGTH
     */
    'description'?: INVALIDSECURITYCODELENGTHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDSECURITYCODELENGTH
     */
    'issue'?: INVALIDSECURITYCODELENGTHIssueEnum;
}

type INVALIDSECURITYCODELENGTHDescriptionEnum = 'The security_code length is invalid for the specified card brand.'
type INVALIDSECURITYCODELENGTHIssueEnum = 'INVALID_SECURITY_CODE_LENGTH'


