/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDIBAN
 */
export interface INVALIDIBAN {
    /**
     * 
     * @type {string}
     * @memberof INVALIDIBAN
     */
    'description'?: INVALIDIBANDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDIBAN
     */
    'issue'?: INVALIDIBANIssueEnum;
}

type INVALIDIBANDescriptionEnum = 'IBAN provided is not a valid bank account number.'
type INVALIDIBANIssueEnum = 'INVALID_IBAN'


