/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDSTRINGLENGTH
 */
export interface INVALIDSTRINGLENGTH {
    /**
     * 
     * @type {string}
     * @memberof INVALIDSTRINGLENGTH
     */
    'description'?: INVALIDSTRINGLENGTHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDSTRINGLENGTH
     */
    'issue'?: INVALIDSTRINGLENGTHIssueEnum;
}

type INVALIDSTRINGLENGTHDescriptionEnum = 'The value of a field is either too short or too long'
type INVALIDSTRINGLENGTHIssueEnum = 'INVALID_STRING_LENGTH'


