/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPICKUPADDRESS
 */
export interface INVALIDPICKUPADDRESS {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPICKUPADDRESS
     */
    'description'?: INVALIDPICKUPADDRESSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPICKUPADDRESS
     */
    'issue'?: INVALIDPICKUPADDRESSIssueEnum;
}

type INVALIDPICKUPADDRESSDescriptionEnum = 'If the \'shipping_option.type\' is set as \'PICKUP\' then the \'shipping_detail.name.full_name\' should start with \'S2S\' meaning Ship To Store. Example: \'S2S My Store\'.'
type INVALIDPICKUPADDRESSIssueEnum = 'INVALID_PICKUP_ADDRESS'


