/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDARRAYMINITEMS
 */
export interface INVALIDARRAYMINITEMS {
    /**
     * 
     * @type {string}
     * @memberof INVALIDARRAYMINITEMS
     */
    'description'?: INVALIDARRAYMINITEMSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDARRAYMINITEMS
     */
    'issue'?: INVALIDARRAYMINITEMSIssueEnum;
}

type INVALIDARRAYMINITEMSDescriptionEnum = 'The number of items in an array parameter is too small.'
type INVALIDARRAYMINITEMSIssueEnum = 'INVALID_ARRAY_MIN_ITEMS'


