/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPARAMETERSYNTAX
 */
export interface INVALIDPARAMETERSYNTAX {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETERSYNTAX
     */
    'description'?: INVALIDPARAMETERSYNTAXDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETERSYNTAX
     */
    'issue'?: INVALIDPARAMETERSYNTAXIssueEnum;
}

type INVALIDPARAMETERSYNTAXDescriptionEnum = 'The value of a field does not conform to the expected format.'
type INVALIDPARAMETERSYNTAXIssueEnum = 'INVALID_PARAMETER_SYNTAX'


