/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDARRAYMAXITEMS
 */
export interface INVALIDARRAYMAXITEMS {
    /**
     * 
     * @type {string}
     * @memberof INVALIDARRAYMAXITEMS
     */
    'description'?: INVALIDARRAYMAXITEMSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDARRAYMAXITEMS
     */
    'issue'?: INVALIDARRAYMAXITEMSIssueEnum;
}

type INVALIDARRAYMAXITEMSDescriptionEnum = 'The number of items in an array parameter is too large.'
type INVALIDARRAYMAXITEMSIssueEnum = 'INVALID_ARRAY_MAX_ITEMS'


