/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDRESOURCEID
 */
export interface INVALIDRESOURCEID {
    /**
     * 
     * @type {string}
     * @memberof INVALIDRESOURCEID
     */
    'description'?: INVALIDRESOURCEIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDRESOURCEID
     */
    'issue'?: INVALIDRESOURCEIDIssueEnum;
}

type INVALIDRESOURCEIDDescriptionEnum = 'Specified resource ID does not exist. Please check the resource ID and try again.'
type INVALIDRESOURCEIDIssueEnum = 'INVALID_RESOURCE_ID'


