/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPLATFORMFEESAMOUNT
 */
export interface INVALIDPLATFORMFEESAMOUNT {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPLATFORMFEESAMOUNT
     */
    'description'?: INVALIDPLATFORMFEESAMOUNTDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPLATFORMFEESAMOUNT
     */
    'issue'?: INVALIDPLATFORMFEESAMOUNTIssueEnum;
}

type INVALIDPLATFORMFEESAMOUNTDescriptionEnum = 'The platform_fees amount cannot be greater than order amount.'
type INVALIDPLATFORMFEESAMOUNTIssueEnum = 'INVALID_PLATFORM_FEES_AMOUNT'


