/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INVALIDPARAMETER
 */
export interface INVALIDPARAMETER {
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETER
     */
    'description'?: INVALIDPARAMETERDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof INVALIDPARAMETER
     */
    'issue'?: INVALIDPARAMETERIssueEnum;
}

type INVALIDPARAMETERDescriptionEnum = 'Cannot be specified as part of the request.'
type INVALIDPARAMETERIssueEnum = 'INVALID_PARAMETER'


