/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ITEMTOTALMISMATCH
 */
export interface ITEMTOTALMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof ITEMTOTALMISMATCH
     */
    'description'?: ITEMTOTALMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ITEMTOTALMISMATCH
     */
    'issue'?: ITEMTOTALMISMATCHIssueEnum;
}

type ITEMTOTALMISMATCHDescriptionEnum = 'Should equal sum of (unit_amount * quantity) across all items for a given purchase_unit.'
type ITEMTOTALMISMATCHIssueEnum = 'ITEM_TOTAL_MISMATCH'


