/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';

/**
 * The details for the items to be purchased.
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * The detailed item description.
     * @type {string}
     * @memberof Item
     */
    'description'?: string;
    /**
     * The item name or title.
     * @type {string}
     * @memberof Item
     */
    'name': string;
    /**
     * 
     * @type {Money}
     * @memberof Item
     */
    'unit_amount': Money;
    /**
     * 
     * @type {Money}
     * @memberof Item
     */
    'tax'?: Money;
    /**
     * The item quantity. Must be a whole number.
     * @type {string}
     * @memberof Item
     */
    'quantity': string;
    /**
     * The stock keeping unit (SKU) for the item.
     * @type {string}
     * @memberof Item
     */
    'sku'?: string;
    /**
     * The item category type.
     * @type {string}
     * @memberof Item
     */
    'category'?: ItemCategoryEnum;
}

type ItemCategoryEnum = 'DIGITAL_GOODS' | 'PHYSICAL_GOODS' | 'DONATION'


