/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ITEMSKUMISMATCH
 */
export interface ITEMSKUMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof ITEMSKUMISMATCH
     */
    'description'?: ITEMSKUMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ITEMSKUMISMATCH
     */
    'issue'?: ITEMSKUMISMATCHIssueEnum;
}

type ITEMSKUMISMATCHDescriptionEnum = 'Item sku must match one of the items sku that was provided during order creation.'
type ITEMSKUMISMATCHIssueEnum = 'ITEM_SKU_MISMATCH'


