/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';

/**
 * 
 * @export
 * @interface LineItemAllOf
 */
export interface LineItemAllOf {
    /**
     * Code used to classify items purchased and track the total amount spent across various categories of products and services. Different corporate purchasing organizations may use different standards, but the United Nations Standard Products and Services Code (UNSPSC) is frequently used.
     * @type {string}
     * @memberof LineItemAllOf
     */
    'commodity_code'?: string;
    /**
     * 
     * @type {Money}
     * @memberof LineItemAllOf
     */
    'discount_amount'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof LineItemAllOf
     */
    'total_amount'?: Money;
    /**
     * Unit of measure is a standard used to express the magnitude of a quantity in international trade. Most commonly used (but not limited to) examples are: Acre (ACR), Ampere (AMP), Centigram (CGM), Centimetre (CMT), Cubic inch (INQ), Cubic metre (MTQ), Fluid ounce (OZA), Foot (FOT), Hour (HUR), Item (ITM), Kilogram (KGM), Kilometre (KMT), Kilowatt (KWT), Liquid gallon (GLL), Liter (LTR), Pounds (LBS), Square foot (FTK).
     * @type {string}
     * @memberof LineItemAllOf
     */
    'unit_of_measure'?: string;
}

