/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MALFORMEDREQUESTJSON
 */
export interface MALFORMEDREQUESTJSON {
    /**
     * 
     * @type {string}
     * @memberof MALFORMEDREQUESTJSON
     */
    'description'?: MALFORMEDREQUESTJSONDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MALFORMEDREQUESTJSON
     */
    'issue'?: MALFORMEDREQUESTJSONIssueEnum;
}

type MALFORMEDREQUESTJSONDescriptionEnum = 'The request JSON is not well formed.'
type MALFORMEDREQUESTJSONIssueEnum = 'MALFORMED_REQUEST_JSON'


