/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MAXAUTHORIZATIONCOUNTEXCEEDED
 */
export interface MAXAUTHORIZATIONCOUNTEXCEEDED {
    /**
     * 
     * @type {string}
     * @memberof MAXAUTHORIZATIONCOUNTEXCEEDED
     */
    'description'?: MAXAUTHORIZATIONCOUNTEXCEEDEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MAXAUTHORIZATIONCOUNTEXCEEDED
     */
    'issue'?: MAXAUTHORIZATIONCOUNTEXCEEDEDIssueEnum;
}

type MAXAUTHORIZATIONCOUNTEXCEEDEDDescriptionEnum = 'Maximum number of authorization allowed for the order is reached. Please contact Customer Support if you need to increase your limit.'
type MAXAUTHORIZATIONCOUNTEXCEEDEDIssueEnum = 'MAX_AUTHORIZATION_COUNT_EXCEEDED'


