/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITS
 */
export interface MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITS {
    /**
     * 
     * @type {string}
     * @memberof MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITS
     */
    'description'?: MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITS
     */
    'issue'?: MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITSIssueEnum;
}

type MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITSDescriptionEnum = '`stored_payment_source.payment_initiator` = `MERCHANT` is not supported if more than one purchase_unit is present in the Order. Merchant initiated payments are not supported from orders with more than one purchase_unit. Please retry the request with multiple Order requests (one for each purchase_unit).'
type MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITSIssueEnum = 'MERCHANT_INITIATED_WITH_MULTIPLE_PURCHASE_UNITS'


