/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MISMATCHEDVAULTIDTOPAYMENTSOURCE
 */
export interface MISMATCHEDVAULTIDTOPAYMENTSOURCE {
    /**
     * 
     * @type {string}
     * @memberof MISMATCHEDVAULTIDTOPAYMENTSOURCE
     */
    'description'?: MISMATCHEDVAULTIDTOPAYMENTSOURCEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MISMATCHEDVAULTIDTOPAYMENTSOURCE
     */
    'issue'?: MISMATCHEDVAULTIDTOPAYMENTSOURCEIssueEnum;
}

type MISMATCHEDVAULTIDTOPAYMENTSOURCEDescriptionEnum = 'The vault_id does not match the payment_source provided. Please verify that the vault_id token used refers to the matching payment_source and try again. For example, a PayPal token cannot be passed in the vault_id field in the payment_source.card object.'
type MISMATCHEDVAULTIDTOPAYMENTSOURCEIssueEnum = 'MISMATCHED_VAULT_ID_TO_PAYMENT_SOURCE'


