/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MISSINGPREVIOUSREFERENCE
 */
export interface MISSINGPREVIOUSREFERENCE {
    /**
     * 
     * @type {string}
     * @memberof MISSINGPREVIOUSREFERENCE
     */
    'description'?: MISSINGPREVIOUSREFERENCEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MISSINGPREVIOUSREFERENCE
     */
    'issue'?: MISSINGPREVIOUSREFERENCEIssueEnum;
}

type MISSINGPREVIOUSREFERENCEDescriptionEnum = 'For Merchant initiated network token transactions, either the payment_source.card.stored_credential.previous_network_transaction_reference or payment_source.card.stored_credential.previous_transaction_reference must be included in the request.'
type MISSINGPREVIOUSREFERENCEIssueEnum = 'MISSING_PREVIOUS_REFERENCE'


