/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MISSINGREQUIREDPARAMETER2
 */
export interface MISSINGREQUIREDPARAMETER2 {
    /**
     * 
     * @type {string}
     * @memberof MISSINGREQUIREDPARAMETER2
     */
    'description'?: MISSINGREQUIREDPARAMETER2DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MISSINGREQUIREDPARAMETER2
     */
    'issue'?: MISSINGREQUIREDPARAMETER2IssueEnum;
}

type MISSINGREQUIREDPARAMETER2DescriptionEnum = 'A required field / parameter is missing'
type MISSINGREQUIREDPARAMETER2IssueEnum = 'MISSING_REQUIRED_PARAMETER'


