/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MISSINGCRYPTOGRAM
 */
export interface MISSINGCRYPTOGRAM {
    /**
     * 
     * @type {string}
     * @memberof MISSINGCRYPTOGRAM
     */
    'description'?: MISSINGCRYPTOGRAMDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MISSINGCRYPTOGRAM
     */
    'issue'?: MISSINGCRYPTOGRAMIssueEnum;
}

type MISSINGCRYPTOGRAMDescriptionEnum = 'Cryptogram is mandatory for any customer initiated network token transactions.'
type MISSINGCRYPTOGRAMIssueEnum = 'MISSING_CRYPTOGRAM'


