/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MISSINGREQUIREDPARAMETER3
 */
export interface MISSINGREQUIREDPARAMETER3 {
    /**
     * 
     * @type {string}
     * @memberof MISSINGREQUIREDPARAMETER3
     */
    'description'?: MISSINGREQUIREDPARAMETER3DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MISSINGREQUIREDPARAMETER3
     */
    'issue'?: MISSINGREQUIREDPARAMETER3IssueEnum;
}

type MISSINGREQUIREDPARAMETER3DescriptionEnum = 'A required field or parameter is missing.'
type MISSINGREQUIREDPARAMETER3IssueEnum = 'MISSING_REQUIRED_PARAMETER'


