/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MISSINGPICKUPADDRESS
 */
export interface MISSINGPICKUPADDRESS {
    /**
     * 
     * @type {string}
     * @memberof MISSINGPICKUPADDRESS
     */
    'description'?: MISSINGPICKUPADDRESSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MISSINGPICKUPADDRESS
     */
    'issue'?: MISSINGPICKUPADDRESSIssueEnum;
}

type MISSINGPICKUPADDRESSDescriptionEnum = 'A pickup address(`shipping.address`) is required for the provided `shipping.type`.'
type MISSINGPICKUPADDRESSIssueEnum = 'MISSING_PICKUP_ADDRESS'


