/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model404DetailsInner } from './model404-details-inner';

/**
 * 
 * @export
 * @interface Model404
 */
export interface Model404 {
    /**
     * 
     * @type {Array<Model404DetailsInner>}
     * @memberof Model404
     */
    'details'?: Array<Model404DetailsInner>;
}

