/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model400DetailsInner } from './model400-details-inner';

/**
 * 
 * @export
 * @interface Model400
 */
export interface Model400 {
    /**
     * 
     * @type {Array<Model400DetailsInner>}
     * @memberof Model400
     */
    'details'?: Array<Model400DetailsInner>;
}

