/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model403DetailsInner } from './model403-details-inner';

/**
 * 
 * @export
 * @interface Model403
 */
export interface Model403 {
    /**
     * 
     * @type {Array<Model403DetailsInner>}
     * @memberof Model403
     */
    'details'?: Array<Model403DetailsInner>;
}

