/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NOTENABLEDFORCARDPROCESSING } from './notenabledforcardprocessing';
import { PAYEEACCOUNTNOTVERIFIED } from './payeeaccountnotverified';
import { PERMISSIONDENIED } from './permissiondenied';

/**
 * @type Model403DetailsInner
 * @export
 */
export type Model403DetailsInner = PERMISSIONDENIED | NOTENABLEDFORCARDPROCESSING | PAYEEACCOUNTNOTVERIFIED;


