/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MSPNOTSUPPORTED
 */
export interface MSPNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof MSPNOTSUPPORTED
     */
    'description'?: MSPNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MSPNOTSUPPORTED
     */
    'issue'?: MSPNOTSUPPORTEDIssueEnum;
}

type MSPNOTSUPPORTEDDescriptionEnum = 'Multiple purchase units are not supported for this operation.'
type MSPNOTSUPPORTEDIssueEnum = 'MSP_NOT_SUPPORTED'


