/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MULTICURRENCYORDER
 */
export interface MULTICURRENCYORDER {
    /**
     * 
     * @type {string}
     * @memberof MULTICURRENCYORDER
     */
    'description'?: MULTICURRENCYORDERDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MULTICURRENCYORDER
     */
    'issue'?: MULTICURRENCYORDERIssueEnum;
}

type MULTICURRENCYORDERDescriptionEnum = 'Multiple differing values of currency_code are not supported. Entire Order request must have the same currency_code.'
type MULTICURRENCYORDERIssueEnum = 'MULTI_CURRENCY_ORDER'


