/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MULTIPLESHIPPINGOPTIONSELECTED
 */
export interface MULTIPLESHIPPINGOPTIONSELECTED {
    /**
     * 
     * @type {string}
     * @memberof MULTIPLESHIPPINGOPTIONSELECTED
     */
    'description'?: MULTIPLESHIPPINGOPTIONSELECTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MULTIPLESHIPPINGOPTIONSELECTED
     */
    'issue'?: MULTIPLESHIPPINGOPTIONSELECTEDIssueEnum;
}

type MULTIPLESHIPPINGOPTIONSELECTEDDescriptionEnum = 'Only one shipping.option can be set to \'selected = true\'.'
type MULTIPLESHIPPINGOPTIONSELECTEDIssueEnum = 'MULTIPLE_SHIPPING_OPTION_SELECTED'


