/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MULTIPLESHIPPINGTYPENOTSUPPORTED
 */
export interface MULTIPLESHIPPINGTYPENOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof MULTIPLESHIPPINGTYPENOTSUPPORTED
     */
    'description'?: MULTIPLESHIPPINGTYPENOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MULTIPLESHIPPINGTYPENOTSUPPORTED
     */
    'issue'?: MULTIPLESHIPPINGTYPENOTSUPPORTEDIssueEnum;
}

type MULTIPLESHIPPINGTYPENOTSUPPORTEDDescriptionEnum = 'Different `shipping.type` are not supported across purchase units.'
type MULTIPLESHIPPINGTYPENOTSUPPORTEDIssueEnum = 'MULTIPLE_SHIPPING_TYPE_NOT_SUPPORTED'


