/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The name of the party.
 * @export
 * @interface Name2
 */
export interface Name2 {
    /**
     * The prefix, or title, to the party\'s name.
     * @type {string}
     * @memberof Name2
     */
    'prefix'?: string;
    /**
     * When the party is a person, the party\'s given, or first, name.
     * @type {string}
     * @memberof Name2
     */
    'given_name'?: string;
    /**
     * When the party is a person, the party\'s surname or family name. Also known as the last name. Required when the party is a person. Use also to store multiple surnames including the matronymic, or mother\'s, surname.
     * @type {string}
     * @memberof Name2
     */
    'surname'?: string;
    /**
     * When the party is a person, the party\'s middle name. Use also to store multiple middle names including the patronymic, or father\'s, middle name.
     * @type {string}
     * @memberof Name2
     */
    'middle_name'?: string;
    /**
     * The suffix for the party\'s name.
     * @type {string}
     * @memberof Name2
     */
    'suffix'?: string;
    /**
     * When the party is a person, the party\'s full name.
     * @type {string}
     * @memberof Name2
     */
    'full_name'?: string;
}

