/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The name of the party.
 * @export
 * @interface Name
 */
export interface Name {
    /**
     * The prefix, or title, to the party\'s name.
     * @type {string}
     * @memberof Name
     */
    'prefix'?: string;
    /**
     * When the party is a person, the party\'s given, or first, name.
     * @type {string}
     * @memberof Name
     */
    'given_name'?: string;
    /**
     * When the party is a person, the party\'s surname or family name. Also known as the last name. Required when the party is a person. Use also to store multiple surnames including the matronymic, or mother\'s, surname.
     * @type {string}
     * @memberof Name
     */
    'surname'?: string;
    /**
     * When the party is a person, the party\'s middle name. Use also to store multiple middle names including the patronymic, or father\'s, middle name.
     * @type {string}
     * @memberof Name
     */
    'middle_name'?: string;
    /**
     * The suffix for the party\'s name.
     * @type {string}
     * @memberof Name
     */
    'suffix'?: string;
    /**
     * DEPRECATED. The party\'s alternate name. Can be a business name, nickname, or any other name that cannot be split into first, last name. Required when the party is a business.
     * @type {string}
     * @memberof Name
     */
    'alternate_full_name'?: string;
    /**
     * When the party is a person, the party\'s full name.
     * @type {string}
     * @memberof Name
     */
    'full_name'?: string;
}

