/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EciFlag } from './eci-flag';

/**
 * The Third Party Network token used to fund a payment.
 * @export
 * @interface NetworkTokenRequest
 */
export interface NetworkTokenRequest {
    /**
     * Third party network token number.
     * @type {string}
     * @memberof NetworkTokenRequest
     */
    'number': string;
    /**
     * The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof NetworkTokenRequest
     */
    'expiry': string;
    /**
     * An Encrypted one-time use value that\'s sent along with Network Token. This field is not required to be present for recurring transactions.
     * @type {string}
     * @memberof NetworkTokenRequest
     */
    'cryptogram'?: string;
    /**
     * Electronic Commerce Indicator (ECI). The ECI value is part of the 2 data elements that indicate the transaction was processed electronically. This should be passed on the authorization transaction to the Gateway/Processor.
     * @type {EciFlag}
     * @memberof NetworkTokenRequest
     */
    'eci_flag'?: EciFlag;
    /**
     * A TRID, or a Token Requestor ID, is an identifier used by merchants to request network tokens from card networks. A TRID is a precursor to obtaining a network token for a credit card primary account number (PAN), and will aid in enabling secure card on file (COF) payments and reducing fraud.
     * @type {string}
     * @memberof NetworkTokenRequest
     */
    'token_requestor_id'?: string;
}

