/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING
 */
export interface NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING {
    /**
     * 
     * @type {string}
     * @memberof NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING
     */
    'description'?: NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSINGDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING
     */
    'issue'?: NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSINGIssueEnum;
}

type NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSINGDescriptionEnum = 'API caller is not enable to process payments using `paypal_transaction_id`. Please contact customer support to request permissions to process transactions with PayPal transaction ID.'
type NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSINGIssueEnum = 'NOT_ELIGIBLE_FOR_PAYPAL_TRANSACTION_ID_PROCESSING'


