/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NOTELIGIBLEFORTOKENPROCESSING
 */
export interface NOTELIGIBLEFORTOKENPROCESSING {
    /**
     * 
     * @type {string}
     * @memberof NOTELIGIBLEFORTOKENPROCESSING
     */
    'description'?: NOTELIGIBLEFORTOKENPROCESSINGDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof NOTELIGIBLEFORTOKENPROCESSING
     */
    'issue'?: NOTELIGIBLEFORTOKENPROCESSINGIssueEnum;
}

type NOTELIGIBLEFORTOKENPROCESSINGDescriptionEnum = 'API caller is not enabled to process payments with the specified type of token. Please contact customer support to request permissions to process transactions with this type of token.'
type NOTELIGIBLEFORTOKENPROCESSINGIssueEnum = 'NOT_ELIGIBLE_FOR_TOKEN_PROCESSING'


