/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NOTENABLEDFORCARDPROCESSING
 */
export interface NOTENABLEDFORCARDPROCESSING {
    /**
     * 
     * @type {string}
     * @memberof NOTENABLEDFORCARDPROCESSING
     */
    'description'?: NOTENABLEDFORCARDPROCESSINGDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof NOTENABLEDFORCARDPROCESSING
     */
    'issue'?: NOTENABLEDFORCARDPROCESSINGIssueEnum;
}

type NOTENABLEDFORCARDPROCESSINGDescriptionEnum = 'The recipient for which the API call is made on behalf of is not enabled for card processing. Please contact PayPal customer support.'
type NOTENABLEDFORCARDPROCESSINGIssueEnum = 'NOT_ENABLED_FOR_CARD_PROCESSING'


