/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NOTENABLEDFORGOOGLEPAY
 */
export interface NOTENABLEDFORGOOGLEPAY {
    /**
     * 
     * @type {string}
     * @memberof NOTENABLEDFORGOOGLEPAY
     */
    'description'?: NOTENABLEDFORGOOGLEPAYDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof NOTENABLEDFORGOOGLEPAY
     */
    'issue'?: NOTENABLEDFORGOOGLEPAYIssueEnum;
}

type NOTENABLEDFORGOOGLEPAYDescriptionEnum = 'The \'API caller\' and/or \'payee\' is not setup to be able to process google pay. Please contact your Account Manager.'
type NOTENABLEDFORGOOGLEPAYIssueEnum = 'NOT_ENABLED_FOR_GOOGLE_PAY'


