/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ONLYONEBANKSOURCEALLOWED
 */
export interface ONLYONEBANKSOURCEALLOWED {
    /**
     * 
     * @type {string}
     * @memberof ONLYONEBANKSOURCEALLOWED
     */
    'description'?: ONLYONEBANKSOURCEALLOWEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ONLYONEBANKSOURCEALLOWED
     */
    'issue'?: ONLYONEBANKSOURCEALLOWEDIssueEnum;
}

type ONLYONEBANKSOURCEALLOWEDDescriptionEnum = 'More than one payment method within the bank payment object is not supported.'
type ONLYONEBANKSOURCEALLOWEDIssueEnum = 'ONLY_ONE_BANK_SOURCE_ALLOWED'


