/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ONLYONEPAYMENTSOURCEALLOWED
 */
export interface ONLYONEPAYMENTSOURCEALLOWED {
    /**
     * 
     * @type {string}
     * @memberof ONLYONEPAYMENTSOURCEALLOWED
     */
    'description'?: ONLYONEPAYMENTSOURCEALLOWEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ONLYONEPAYMENTSOURCEALLOWED
     */
    'issue'?: ONLYONEPAYMENTSOURCEALLOWEDIssueEnum;
}

type ONLYONEPAYMENTSOURCEALLOWEDDescriptionEnum = 'More than one payment method within the payment source is not supported.'
type ONLYONEPAYMENTSOURCEALLOWEDIssueEnum = 'ONLY_ONE_PAYMENT_SOURCE_ALLOWED'


