/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERALREADYAUTHORIZED1
 */
export interface ORDERALREADYAUTHORIZED1 {
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYAUTHORIZED1
     */
    'description'?: ORDERALREADYAUTHORIZED1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYAUTHORIZED1
     */
    'issue'?: ORDERALREADYAUTHORIZED1IssueEnum;
}

type ORDERALREADYAUTHORIZED1DescriptionEnum = 'Order already authorized.If \'intent=AUTHORIZE\' only one authorization per order is allowed.'
type ORDERALREADYAUTHORIZED1IssueEnum = 'ORDER_ALREADY_AUTHORIZED'


