/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AMOUNTNOTPATCHABLE } from './amountnotpatchable';
import { FIELDNOTPATCHABLE } from './fieldnotpatchable';
import { INVALIDARRAYMAXITEMS } from './invalidarraymaxitems';
import { INVALIDPARAMETERSYNTAX } from './invalidparametersyntax';
import { INVALIDPARAMETERVALUE1 } from './invalidparametervalue1';
import { INVALIDPATCHOPERATION } from './invalidpatchoperation';
import { INVALIDSTRINGLENGTH } from './invalidstringlength';
import { MALFORMEDREQUESTJSON } from './malformedrequestjson';
import { MISSINGREQUIREDPARAMETER1 } from './missingrequiredparameter1';

/**
 * @type OrdersPatch400DetailsInner
 * @export
 */
export type OrdersPatch400DetailsInner = FIELDNOTPATCHABLE | INVALIDARRAYMAXITEMS | INVALIDPARAMETERSYNTAX | INVALIDSTRINGLENGTH | INVALIDPARAMETERVALUE1 | MISSINGREQUIREDPARAMETER1 | AMOUNTNOTPATCHABLE | INVALIDPATCHOPERATION | MALFORMEDREQUESTJSON;


