/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ALIASDECLINEDBYPROCESSOR } from './aliasdeclinedbyprocessor';
import { APPLEPAYAMOUNTMISMATCH } from './applepayamountmismatch';
import { BANKNOTSUPPORTEDFORVERIFICATION } from './banknotsupportedforverification';
import { BILLINGADDRESSINVALID } from './billingaddressinvalid';
import { BLIKONECLICKMISSINGREQUIREDPARAMETER } from './blikoneclickmissingrequiredparameter';
import { CANCELURLREQUIRED } from './cancelurlrequired';
import { CARDEXPIRED } from './cardexpired';
import { CARDEXPIRYREQUIRED } from './cardexpiryrequired';
import { CARDNUMBERREQUIRED } from './cardnumberrequired';
import { CARDTYPENOTSUPPORTED } from './cardtypenotsupported';
import { COUNTRYNOTSUPPORTEDBYPAYMENTSOURCE } from './countrynotsupportedbypaymentsource';
import { CRYPTOGRAMREQUIRED } from './cryptogramrequired';
import { CURRENCYNOTSUPPORTEDFORBANK } from './currencynotsupportedforbank';
import { CURRENCYNOTSUPPORTEDFORCARDTYPE } from './currencynotsupportedforcardtype';
import { CURRENCYNOTSUPPORTEDFORCOUNTRY } from './currencynotsupportedforcountry';
import { DEVICEDATANOTAVAILABLE } from './devicedatanotavailable';
import { EMVDATAREQUIRED } from './emvdatarequired';
import { GOOGLEPAYGATEWAYMERCHANTIDMISMATCH } from './googlepaygatewaymerchantidmismatch';
import { IBANCOUNTRYNOTSUPPORTED } from './ibancountrynotsupported';
import { INCOMPATIBLEPARAMETERVALUE } from './incompatibleparametervalue';
import { INVALIDEXPIRYDATE } from './invalidexpirydate';
import { INVALIDGOOGLEPAYTOKEN } from './invalidgooglepaytoken';
import { INVALIDIBAN } from './invalidiban';
import { INVALIDSECURITYCODELENGTH } from './invalidsecuritycodelength';
import { ITEMCATEGORYNOTSUPPORTEDBYPAYMENTSOURCE } from './itemcategorynotsupportedbypaymentsource';
import { MISMATCHEDVAULTIDTOPAYMENTSOURCE } from './mismatchedvaultidtopaymentsource';
import { MISSINGCRYPTOGRAM } from './missingcryptogram';
import { MISSINGPREVIOUSREFERENCE } from './missingpreviousreference';
import { NOPAYMENTSOURCEPROVIDED } from './nopaymentsourceprovided';
import { NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING } from './noteligibleforpaypaltransactionidprocessing';
import { NOTELIGIBLEFORPNREFPROCESSING } from './noteligibleforpnrefprocessing';
import { NOTENABLEDTOVAULTPAYMENTSOURCE } from './notenabledtovaultpaymentsource';
import { ONEOFPARAMETERSREQUIRED } from './oneofparametersrequired';
import { ONEOFTHEPARAMETERSREQUIRED } from './oneoftheparametersrequired';
import { ONLYONEBANKSOURCEALLOWED } from './onlyonebanksourceallowed';
import { ONLYONEPAYMENTSOURCEALLOWED } from './onlyonepaymentsourceallowed';
import { ORDERALREADYAUTHORIZED } from './orderalreadyauthorized';
import { ORDERALREADYCAPTURED } from './orderalreadycaptured';
import { ORDERCANNOTBECONFIRMED } from './ordercannotbeconfirmed';
import { ORDERCOMPLETEONPAYMENTAPPROVAL1 } from './ordercompleteonpaymentapproval1';
import { ORDERISPENDINGAPPROVAL } from './orderispendingapproval';
import { PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCE } from './payeecountrynotsupportedforpaymentsource';
import { PAYMENTALREADYAPPROVED } from './paymentalreadyapproved';
import { PAYMENTSOURCECANNOTBEUSED } from './paymentsourcecannotbeused';
import { PAYMENTSOURCEDECLINEDBYPROCESSOR } from './paymentsourcedeclinedbyprocessor';
import { PAYMENTSOURCEINFOCANNOTBEVERIFIED } from './paymentsourceinfocannotbeverified';
import { PAYPALTRANSACTIONIDNOTFOUND } from './paypaltransactionidnotfound';
import { PNREFNOTFOUND } from './pnrefnotfound';
import { REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT } from './requiredparameterforcustomerinitiatedpayment';
import { REQUIREDPARAMETERFORPAYMENTSOURCE } from './requiredparameterforpaymentsource';
import { RETURNURLREQUIRED } from './returnurlrequired';
import { SETUPERRORFORBANK } from './setuperrorforbank';
import { SHIPPINGADDRESSINVALID } from './shippingaddressinvalid';
import { TOKENEXPIRED } from './tokenexpired';
import { TRANSACTIONLIMITEXCEEDED } from './transactionlimitexceeded';
import { UNSUPPORTEDPROCESSINGINSTRUCTION } from './unsupportedprocessinginstruction';
import { VAULTINSTRUCTIONDUPLICATED } from './vaultinstructionduplicated';
import { VAULTINSTRUCTIONREQUIRED } from './vaultinstructionrequired';

/**
 * @type OrdersConfirm422DetailsInner
 * @export
 */
export type OrdersConfirm422DetailsInner = ORDERALREADYCAPTURED | ORDERALREADYAUTHORIZED | ORDERCANNOTBECONFIRMED | MISSINGPREVIOUSREFERENCE | MISSINGCRYPTOGRAM | CURRENCYNOTSUPPORTEDFORCOUNTRY | CARDEXPIRED | CARDTYPENOTSUPPORTED | CURRENCYNOTSUPPORTEDFORCARDTYPE | ONLYONEPAYMENTSOURCEALLOWED | NOPAYMENTSOURCEPROVIDED | PAYMENTALREADYAPPROVED | UNSUPPORTEDPROCESSINGINSTRUCTION | ORDERCOMPLETEONPAYMENTAPPROVAL1 | INVALIDEXPIRYDATE | TOKENEXPIRED | INVALIDGOOGLEPAYTOKEN | GOOGLEPAYGATEWAYMERCHANTIDMISMATCH | CRYPTOGRAMREQUIRED | ONEOFPARAMETERSREQUIRED | RETURNURLREQUIRED | CANCELURLREQUIRED | COUNTRYNOTSUPPORTEDBYPAYMENTSOURCE | REQUIREDPARAMETERFORPAYMENTSOURCE | REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT | ITEMCATEGORYNOTSUPPORTEDBYPAYMENTSOURCE | PAYMENTSOURCEINFOCANNOTBEVERIFIED | PAYMENTSOURCEDECLINEDBYPROCESSOR | PAYMENTSOURCECANNOTBEUSED | SETUPERRORFORBANK | BANKNOTSUPPORTEDFORVERIFICATION | APPLEPAYAMOUNTMISMATCH | ONEOFTHEPARAMETERSREQUIRED | BILLINGADDRESSINVALID | SHIPPINGADDRESSINVALID | ORDERISPENDINGAPPROVAL | DEVICEDATANOTAVAILABLE | CURRENCYNOTSUPPORTEDFORBANK | ONLYONEBANKSOURCEALLOWED | INVALIDIBAN | IBANCOUNTRYNOTSUPPORTED | PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCE | CARDNUMBERREQUIRED | CARDEXPIRYREQUIRED | INCOMPATIBLEPARAMETERVALUE | VAULTINSTRUCTIONDUPLICATED | VAULTINSTRUCTIONREQUIRED | MISMATCHEDVAULTIDTOPAYMENTSOURCE | NOTELIGIBLEFORPNREFPROCESSING | NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING | PAYPALTRANSACTIONIDNOTFOUND | PNREFNOTFOUND | INVALIDSECURITYCODELENGTH | NOTENABLEDTOVAULTPAYMENTSOURCE | EMVDATAREQUIRED | ALIASDECLINEDBYPROCESSOR | BLIKONECLICKMISSINGREQUIREDPARAMETER | TRANSACTIONLIMITEXCEEDED;


