/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersAuthorize403DetailsInner } from './orders-authorize403-details-inner';

/**
 * 
 * @export
 * @interface OrdersAuthorize403
 */
export interface OrdersAuthorize403 {
    /**
     * 
     * @type {Array<OrdersAuthorize403DetailsInner>}
     * @memberof OrdersAuthorize403
     */
    'details'?: Array<OrdersAuthorize403DetailsInner>;
}

