/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersTrackersPatch404DetailsInner } from './orders-trackers-patch404-details-inner';

/**
 * 
 * @export
 * @interface OrdersTrackersPatch404
 */
export interface OrdersTrackersPatch404 {
    /**
     * 
     * @type {Array<OrdersTrackersPatch404DetailsInner>}
     * @memberof OrdersTrackersPatch404
     */
    'details'?: Array<OrdersTrackersPatch404DetailsInner>;
}

