/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERCANNOTBESAVED
 */
export interface ORDERCANNOTBESAVED {
    /**
     * 
     * @type {string}
     * @memberof ORDERCANNOTBESAVED
     */
    'description'?: ORDERCANNOTBESAVEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERCANNOTBESAVED
     */
    'issue'?: ORDERCANNOTBESAVEDIssueEnum;
}

type ORDERCANNOTBESAVEDDescriptionEnum = 'The option to save an order is only available if the `intent` is AUTHORIZE and `processing_instruction` uses one of the `ORDER_SAVED` options. For example, `intent`=AUTHORIZE, `processing_instruction`=ORDER_SAVED_EXPLICITLY. Please change the intent and/or processing_instruction` and try again.'
type ORDERCANNOTBESAVEDIssueEnum = 'ORDER_CANNOT_BE_SAVED'


