/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersConfirm400DetailsInner } from './orders-confirm400-details-inner';

/**
 * 
 * @export
 * @interface OrdersConfirm400
 */
export interface OrdersConfirm400 {
    /**
     * 
     * @type {Array<OrdersConfirm400DetailsInner>}
     * @memberof OrdersConfirm400
     */
    'details'?: Array<OrdersConfirm400DetailsInner>;
}

