/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersTrackCreate422DetailsInner } from './orders-track-create422-details-inner';

/**
 * 
 * @export
 * @interface OrdersTrackCreate422
 */
export interface OrdersTrackCreate422 {
    /**
     * 
     * @type {Array<OrdersTrackCreate422DetailsInner>}
     * @memberof OrdersTrackCreate422
     */
    'details'?: Array<OrdersTrackCreate422DetailsInner>;
}

