/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error400 } from './error400';
import { ErrorLinkDescription } from './error-link-description';
import { Model400 } from './model400';
import { Model400DetailsInner } from './model400-details-inner';

/**
 * @type OrdersCreateOrderResponse
 * @export
 */
export type OrdersCreateOrderResponse = Error400 & Model400;


