/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INVALIDCOUNTRYCODE } from './invalidcountrycode';
import { INVALIDPARAMETERSYNTAX } from './invalidparametersyntax';
import { INVALIDPARAMETERVALUE } from './invalidparametervalue';
import { INVALIDSTRINGLENGTH } from './invalidstringlength';
import { MALFORMEDREQUESTJSON } from './malformedrequestjson';
import { MISSINGREQUIREDPARAMETER2 } from './missingrequiredparameter2';

/**
 * @type OrdersAuthorize400DetailsInner
 * @export
 */
export type OrdersAuthorize400DetailsInner = INVALIDCOUNTRYCODE | INVALIDPARAMETERVALUE | MISSINGREQUIREDPARAMETER2 | INVALIDSTRINGLENGTH | INVALIDPARAMETERSYNTAX | MALFORMEDREQUESTJSON;


