/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERALREADYCAPTURED
 */
export interface ORDERALREADYCAPTURED {
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYCAPTURED
     */
    'description'?: ORDERALREADYCAPTUREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYCAPTURED
     */
    'issue'?: ORDERALREADYCAPTUREDIssueEnum;
}

type ORDERALREADYCAPTUREDDescriptionEnum = 'Order already captured. If \'intent=CAPTURE\' only one capture per order is allowed.'
type ORDERALREADYCAPTUREDIssueEnum = 'ORDER_ALREADY_CAPTURED'


