/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutPaymentIntent } from './checkout-payment-intent';
import { LinkDescription } from './link-description';
import { OrderStatus } from './order-status';
import { Payer } from './payer';
import { PaymentSourceResponse } from './payment-source-response';
import { ProcessingInstruction } from './processing-instruction';
import { PurchaseUnit } from './purchase-unit';

/**
 * 
 * @export
 * @interface OrderAllOf
 */
export interface OrderAllOf {
    /**
     * The ID of the order.
     * @type {string}
     * @memberof OrderAllOf
     */
    'id'?: string;
    /**
     * 
     * @type {PaymentSourceResponse}
     * @memberof OrderAllOf
     */
    'payment_source'?: PaymentSourceResponse;
    /**
     * The intent to either capture payment immediately or authorize a payment for an order after order creation.
     * @type {CheckoutPaymentIntent}
     * @memberof OrderAllOf
     */
    'intent'?: CheckoutPaymentIntent;
    /**
     * The instruction to process an order.
     * @type {ProcessingInstruction}
     * @memberof OrderAllOf
     */
    'processing_instruction'?: ProcessingInstruction;
    /**
     * 
     * @type {Payer}
     * @memberof OrderAllOf
     */
    'payer'?: Payer;
    /**
     * An array of purchase units. Each purchase unit establishes a contract between a customer and merchant. Each purchase unit represents either a full or partial order that the customer intends to purchase from the merchant.
     * @type {Array<PurchaseUnit>}
     * @memberof OrderAllOf
     */
    'purchase_units'?: Array<PurchaseUnit>;
    /**
     * The order status.
     * @type {OrderStatus}
     * @memberof OrderAllOf
     */
    'status'?: OrderStatus;
    /**
     * An array of request-related HATEOAS links. To complete payer approval, use the `approve` link to redirect the payer. The API caller has 3 hours (default setting, this which can be changed by your account manager to 24/48/72 hours to accommodate your use case) from the time the order is created, to redirect your payer. Once redirected, the API caller has 3 hours for the payer to approve the order and either authorize or capture the order. If you are not using the PayPal JavaScript SDK to initiate PayPal Checkout (in context) ensure that you include `application_context.return_url` is specified or you will get \"We\'re sorry, Things don\'t appear to be working at the moment\" after the payer approves the payment.
     * @type {Array<LinkDescription>}
     * @memberof OrderAllOf
     */
    'links'?: Array<LinkDescription>;
}

