/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERNOTAPPROVED
 */
export interface ORDERNOTAPPROVED {
    /**
     * 
     * @type {string}
     * @memberof ORDERNOTAPPROVED
     */
    'description'?: ORDERNOTAPPROVEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERNOTAPPROVED
     */
    'issue'?: ORDERNOTAPPROVEDIssueEnum;
}

type ORDERNOTAPPROVEDDescriptionEnum = 'Payer has not yet approved the Order for payment. Please redirect the payer to the \'rel\':\'approve\' url returned as part of the HATEOAS links within the Create Order call.'
type ORDERNOTAPPROVEDIssueEnum = 'ORDER_NOT_APPROVED'


