/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDEREXPIRED
 */
export interface ORDEREXPIRED {
    /**
     * 
     * @type {string}
     * @memberof ORDEREXPIRED
     */
    'description'?: ORDEREXPIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDEREXPIRED
     */
    'issue'?: ORDEREXPIREDIssueEnum;
}

type ORDEREXPIREDDescriptionEnum = 'Order is expired and hence cannot be authorized. Please contact Customer Support if you need to increase your order validity period.'
type ORDEREXPIREDIssueEnum = 'ORDER_EXPIRED'


