/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AMOUNTCHANGENOTALLOWED } from './amountchangenotallowed';
import { AMOUNTMISMATCH } from './amountmismatch';
import { CANNOTBENEGATIVE } from './cannotbenegative';
import { CANNOTBEZEROORNEGATIVE } from './cannotbezeroornegative';
import { CITYREQUIRED } from './cityrequired';
import { DECIMALPRECISION } from './decimalprecision';
import { DONATIONITEMSNOTSUPPORTED } from './donationitemsnotsupported';
import { DUPLICATEREFERENCEID } from './duplicatereferenceid';
import { INVALIDCURRENCYCODE } from './invalidcurrencycode';
import { INVALIDFXRATEID } from './invalidfxrateid';
import { INVALIDJSONPOINTERFORMAT } from './invalidjsonpointerformat';
import { INVALIDPARAMETER } from './invalidparameter';
import { INVALIDPLATFORMFEESACCOUNT } from './invalidplatformfeesaccount';
import { INVALIDPLATFORMFEESAMOUNT } from './invalidplatformfeesamount';
import { ITEMTOTALMISMATCH } from './itemtotalmismatch';
import { ITEMTOTALREQUIRED } from './itemtotalrequired';
import { MAXVALUEEXCEEDED } from './maxvalueexceeded';
import { MULTICURRENCYORDER } from './multicurrencyorder';
import { MULTIPLESHIPPINGOPTIONSELECTED } from './multipleshippingoptionselected';
import { NOTPATCHABLE } from './notpatchable';
import { ORDERALREADYCOMPLETED } from './orderalreadycompleted';
import { PATCHPATHREQUIRED } from './patchpathrequired';
import { PATCHVALUEREQUIRED } from './patchvaluerequired';
import { PAYEEACCOUNTLOCKEDORCLOSED } from './payeeaccountlockedorclosed';
import { PAYEEACCOUNTRESTRICTED } from './payeeaccountrestricted';
import { PAYEEFXRATEIDCURRENCYMISMATCH } from './payeefxrateidcurrencymismatch';
import { PAYEEFXRATEIDEXPIRED } from './payeefxrateidexpired';
import { PLATFORMFEESNOTSUPPORTED } from './platformfeesnotsupported';
import { POSTALCODEREQUIRED } from './postalcoderequired';
import { PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH } from './preferredshippingoptionamountmismatch';
import { REFERENCEIDNOTFOUND } from './referenceidnotfound';
import { REFERENCEIDREQUIRED } from './referenceidrequired';
import { SHIPPINGOPTIONNOTSELECTED } from './shippingoptionnotselected';
import { SHIPPINGOPTIONSNOTSUPPORTED1 } from './shippingoptionsnotsupported1';
import { TAXTOTALMISMATCH } from './taxtotalmismatch';
import { TAXTOTALREQUIRED } from './taxtotalrequired';
import { UNSUPPORTEDINTENT } from './unsupportedintent';
import { UNSUPPORTEDPATCHPARAMETERVALUE } from './unsupportedpatchparametervalue';

/**
 * @type OrdersPatch422DetailsInner
 * @export
 */
export type OrdersPatch422DetailsInner = AMOUNTMISMATCH | CANNOTBENEGATIVE | CANNOTBEZEROORNEGATIVE | CITYREQUIRED | DECIMALPRECISION | DONATIONITEMSNOTSUPPORTED | DUPLICATEREFERENCEID | INVALIDCURRENCYCODE | ITEMTOTALMISMATCH | ITEMTOTALREQUIRED | MAXVALUEEXCEEDED | INVALIDJSONPOINTERFORMAT | INVALIDPARAMETER | NOTPATCHABLE | TAXTOTALMISMATCH | TAXTOTALREQUIRED | UNSUPPORTEDINTENT | UNSUPPORTEDPATCHPARAMETERVALUE | PATCHVALUEREQUIRED | PATCHPATHREQUIRED | PAYEEACCOUNTLOCKEDORCLOSED | PAYEEACCOUNTRESTRICTED | PAYEEFXRATEIDEXPIRED | PAYEEFXRATEIDCURRENCYMISMATCH | INVALIDFXRATEID | PLATFORMFEESNOTSUPPORTED | INVALIDPLATFORMFEESACCOUNT | INVALIDPLATFORMFEESAMOUNT | POSTALCODEREQUIRED | REFERENCEIDNOTFOUND | REFERENCEIDREQUIRED | MULTICURRENCYORDER | SHIPPINGOPTIONNOTSELECTED | SHIPPINGOPTIONSNOTSUPPORTED1 | MULTIPLESHIPPINGOPTIONSELECTED | ORDERALREADYCOMPLETED | PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH | AMOUNTCHANGENOTALLOWED;


