/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error403 } from './error403';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersAuthorize403 } from './orders-authorize403';
import { OrdersAuthorize403DetailsInner } from './orders-authorize403-details-inner';

/**
 * @type OrdersAuthorizePaymentOrder403Response
 * @export
 */
export type OrdersAuthorizePaymentOrder403Response = Error403 & OrdersAuthorize403;


