/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityTimestamps } from './activity-timestamps';
import { CheckoutPaymentIntent } from './checkout-payment-intent';
import { LinkDescription } from './link-description';
import { OrderAllOf } from './order-all-of';
import { OrderStatus } from './order-status';
import { Payer } from './payer';
import { PaymentSourceResponse } from './payment-source-response';
import { ProcessingInstruction } from './processing-instruction';
import { PurchaseUnit } from './purchase-unit';

/**
 * @type Order
 * The order details.
 * @export
 */
export type Order = ActivityTimestamps & OrderAllOf;


