/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERALREADYAUTHORIZED
 */
export interface ORDERALREADYAUTHORIZED {
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYAUTHORIZED
     */
    'description'?: ORDERALREADYAUTHORIZEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYAUTHORIZED
     */
    'issue'?: ORDERALREADYAUTHORIZEDIssueEnum;
}

type ORDERALREADYAUTHORIZEDDescriptionEnum = 'Order already captured. If \'intent=CAPTURE\' only one capture per order is allowed.'
type ORDERALREADYAUTHORIZEDIssueEnum = 'ORDER_ALREADY_AUTHORIZED'


