/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AGREEMENTALREADYCANCELLED } from './agreementalreadycancelled';
import { APPLEPAYAMOUNTMISMATCH } from './applepayamountmismatch';
import { AUTHCAPTURENOTENABLED } from './authcapturenotenabled';
import { BANKNOTSUPPORTEDFORVERIFICATION } from './banknotsupportedforverification';
import { BILLINGAGREEMENTIDMISMATCH } from './billingagreementidmismatch';
import { BILLINGAGREEMENTNOTFOUND } from './billingagreementnotfound';
import { CANCELURLREQUIRED } from './cancelurlrequired';
import { CARDBRANDNOTSUPPORTED } from './cardbrandnotsupported';
import { CARDEXPIRYREQUIRED } from './cardexpiryrequired';
import { CARDNUMBERREQUIRED } from './cardnumberrequired';
import { COMPLIANCEVIOLATION } from './complianceviolation';
import { CURRENCYNOTSUPPORTEDFORBANK } from './currencynotsupportedforbank';
import { DECLINEDDUETORELATEDTXN } from './declinedduetorelatedtxn';
import { DOMESTICTRANSACTIONREQUIRED } from './domestictransactionrequired';
import { DUPLICATEINVOICEID } from './duplicateinvoiceid';
import { IBANCOUNTRYNOTSUPPORTED } from './ibancountrynotsupported';
import { IDENTIFIERNOTFOUND } from './identifiernotfound';
import { INCOMPATIBLEPARAMETERVALUE } from './incompatibleparametervalue';
import { INSTRUMENTDECLINED } from './instrumentdeclined';
import { INVALIDIBAN } from './invalidiban';
import { INVALIDPICKUPADDRESS } from './invalidpickupaddress';
import { INVALIDPREVIOUSTRANSACTIONREFERENCE } from './invalidprevioustransactionreference';
import { INVALIDSECURITYCODELENGTH } from './invalidsecuritycodelength';
import { MAXNUMBEROFPAYMENTATTEMPTSEXCEEDED } from './maxnumberofpaymentattemptsexceeded';
import { MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS } from './merchantinitiatedwithauthenticationresults';
import { MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITS } from './merchantinitiatedwithmultiplepurchaseunits';
import { MERCHANTINITIATEDWITHSECURITYCODE } from './merchantinitiatedwithsecuritycode';
import { MISMATCHEDVAULTIDTOPAYMENTSOURCE } from './mismatchedvaultidtopaymentsource';
import { MISSINGCRYPTOGRAM } from './missingcryptogram';
import { MISSINGPREVIOUSREFERENCE } from './missingpreviousreference';
import { NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING } from './noteligibleforpaypaltransactionidprocessing';
import { NOTELIGIBLEFORPNREFPROCESSING } from './noteligibleforpnrefprocessing';
import { NOTENABLEDFORBANKPROCESSING } from './notenabledforbankprocessing';
import { NOTENABLEDFORCARDPROCESSING1 } from './notenabledforcardprocessing1';
import { ONLYONEBANKSOURCEALLOWED } from './onlyonebanksourceallowed';
import { ORDERALREADYCAPTURED1 } from './orderalreadycaptured1';
import { ORDERCOMPLETIONINPROGRESS } from './ordercompletioninprogress';
import { ORDERNOTAPPROVED1 } from './ordernotapproved1';
import { PAYEEBLOCKEDTRANSACTION } from './payeeblockedtransaction';
import { PAYEEFXRATEIDEXPIRED } from './payeefxrateidexpired';
import { PAYEENOTENABLEDFORBANKPROCESSING } from './payeenotenabledforbankprocessing';
import { PAYEENOTENABLEDFORCARDPROCESSING } from './payeenotenabledforcardprocessing';
import { PAYERACCOUNTLOCKEDORCLOSED } from './payeraccountlockedorclosed';
import { PAYERACCOUNTRESTRICTED } from './payeraccountrestricted';
import { PAYERACTIONREQUIRED } from './payeractionrequired';
import { PAYERCANNOTPAY1 } from './payercannotpay1';
import { PAYMENTSOURCEMISMATCH } from './paymentsourcemismatch';
import { PAYMENTSOURCENOTSUPPORTED } from './paymentsourcenotsupported';
import { PAYPALTRANSACTIONIDEXPIRED } from './paypaltransactionidexpired';
import { PAYPALTRANSACTIONIDNOTFOUND } from './paypaltransactionidnotfound';
import { PLATFORMFEEPAYEECANNOTBESAMEASPAYER } from './platformfeepayeecannotbesameaspayer';
import { PNREFEXPIRED } from './pnrefexpired';
import { PNREFNOTFOUND } from './pnrefnotfound';
import { PREFERREDPAYMENTSOURCEMISMATCH } from './preferredpaymentsourcemismatch';
import { PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK } from './previoustransactionreferencehaschargeback';
import { PREVIOUSTRANSACTIONREFERENCEVOIDED } from './previoustransactionreferencevoided';
import { REDIRECTPAYERFORALTERNATEFUNDING } from './redirectpayerforalternatefunding';
import { REFERENCEDCARDEXPIRED } from './referencedcardexpired';
import { REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT } from './requiredparameterforcustomerinitiatedpayment';
import { RETURNURLREQUIRED } from './returnurlrequired';
import { SETUPERRORFORBANK } from './setuperrorforbank';
import { SHIPPINGADDRESSINVALID } from './shippingaddressinvalid';
import { TOKENIDNOTFOUND } from './tokenidnotfound';
import { TRANSACTIONBLOCKEDBYPAYEE } from './transactionblockedbypayee';
import { TRANSACTIONLIMITEXCEEDED } from './transactionlimitexceeded';
import { TRANSACTIONRECEIVINGLIMITEXCEEDED } from './transactionreceivinglimitexceeded';
import { TRANSACTIONREFUSED } from './transactionrefused';
import { VAULTINSTRUCTIONREQUIRED } from './vaultinstructionrequired';

/**
 * @type OrdersCapture422DetailsInner
 * @export
 */
export type OrdersCapture422DetailsInner = AGREEMENTALREADYCANCELLED | BILLINGAGREEMENTNOTFOUND | DECLINEDDUETORELATEDTXN | MISSINGPREVIOUSREFERENCE | MISSINGCRYPTOGRAM | CARDBRANDNOTSUPPORTED | COMPLIANCEVIOLATION | DOMESTICTRANSACTIONREQUIRED | DUPLICATEINVOICEID | INSTRUMENTDECLINED | ORDERNOTAPPROVED1 | MAXNUMBEROFPAYMENTATTEMPTSEXCEEDED | PAYEEBLOCKEDTRANSACTION | PAYEEFXRATEIDEXPIRED | PAYERACCOUNTLOCKEDORCLOSED | PAYERACCOUNTRESTRICTED | PAYERCANNOTPAY1 | PAYPALTRANSACTIONIDEXPIRED | PNREFEXPIRED | REFERENCEDCARDEXPIRED | TOKENIDNOTFOUND | TRANSACTIONLIMITEXCEEDED | TRANSACTIONRECEIVINGLIMITEXCEEDED | TRANSACTIONREFUSED | REDIRECTPAYERFORALTERNATEFUNDING | ORDERALREADYCAPTURED1 | TRANSACTIONBLOCKEDBYPAYEE | AUTHCAPTURENOTENABLED | NOTENABLEDFORBANKPROCESSING | NOTENABLEDFORCARDPROCESSING1 | PAYEENOTENABLEDFORBANKPROCESSING | PAYEENOTENABLEDFORCARDPROCESSING | INVALIDPICKUPADDRESS | SHIPPINGADDRESSINVALID | PAYMENTSOURCENOTSUPPORTED | ORDERCOMPLETIONINPROGRESS | BILLINGAGREEMENTIDMISMATCH | PREFERREDPAYMENTSOURCEMISMATCH | INCOMPATIBLEPARAMETERVALUE | INVALIDPREVIOUSTRANSACTIONREFERENCE | PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK | PREVIOUSTRANSACTIONREFERENCEVOIDED | PAYMENTSOURCEMISMATCH | MERCHANTINITIATEDWITHSECURITYCODE | MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS | MERCHANTINITIATEDWITHMULTIPLEPURCHASEUNITS | RETURNURLREQUIRED | CANCELURLREQUIRED | SETUPERRORFORBANK | BANKNOTSUPPORTEDFORVERIFICATION | PAYERACTIONREQUIRED | APPLEPAYAMOUNTMISMATCH | CURRENCYNOTSUPPORTEDFORBANK | ONLYONEBANKSOURCEALLOWED | INVALIDIBAN | IBANCOUNTRYNOTSUPPORTED | CARDNUMBERREQUIRED | CARDEXPIRYREQUIRED | VAULTINSTRUCTIONREQUIRED | MISMATCHEDVAULTIDTOPAYMENTSOURCE | NOTELIGIBLEFORPNREFPROCESSING | NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING | PAYPALTRANSACTIONIDNOTFOUND | PNREFNOTFOUND | INVALIDSECURITYCODELENGTH | PLATFORMFEEPAYEECANNOTBESAMEASPAYER | REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT | IDENTIFIERNOTFOUND;


