/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERALREADYCAPTURED1
 */
export interface ORDERALREADYCAPTURED1 {
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYCAPTURED1
     */
    'description'?: ORDERALREADYCAPTURED1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERALREADYCAPTURED1
     */
    'issue'?: ORDERALREADYCAPTURED1IssueEnum;
}

type ORDERALREADYCAPTURED1DescriptionEnum = 'Order already captured.If \'intent=CAPTURE\' only one capture per order is allowed.'
type ORDERALREADYCAPTURED1IssueEnum = 'ORDER_ALREADY_CAPTURED'


