/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersCapture400DetailsInner } from './orders-capture400-details-inner';

/**
 * 
 * @export
 * @interface OrdersCapture400
 */
export interface OrdersCapture400 {
    /**
     * 
     * @type {Array<OrdersCapture400DetailsInner>}
     * @memberof OrdersCapture400
     */
    'details'?: Array<OrdersCapture400DetailsInner>;
}

