/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INVALIDPARAMETERSYNTAX } from './invalidparametersyntax';
import { INVALIDPARAMETERVALUE } from './invalidparametervalue';
import { INVALIDSTRINGLENGTH1 } from './invalidstringlength1';
import { MISSINGREQUIREDPARAMETER1 } from './missingrequiredparameter1';

/**
 * @type OrdersTrackCreate400DetailsInner
 * @export
 */
export type OrdersTrackCreate400DetailsInner = MISSINGREQUIREDPARAMETER1 | INVALIDSTRINGLENGTH1 | INVALIDPARAMETERVALUE | INVALIDPARAMETERSYNTAX;


