/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error422 } from './error422';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersTrackCreate422 } from './orders-track-create422';
import { OrdersTrackCreate422DetailsInner } from './orders-track-create422-details-inner';

/**
 * @type OrdersAddTrackingInformation422Response
 * @export
 */
export type OrdersAddTrackingInformation422Response = Error422 & OrdersTrackCreate422;


