/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CONSENTNEEDED } from './consentneeded';
import { NOTELIGIBLEFORTOKENPROCESSING } from './noteligiblefortokenprocessing';
import { PERMISSIONDENIED } from './permissiondenied';
import { PERMISSIONDENIEDFORDONATIONITEMS } from './permissiondeniedfordonationitems';

/**
 * @type OrdersCapture403DetailsInner
 * @export
 */
export type OrdersCapture403DetailsInner = CONSENTNEEDED | NOTELIGIBLEFORTOKENPROCESSING | PERMISSIONDENIED | PERMISSIONDENIEDFORDONATIONITEMS;


