/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentSource } from './payment-source';

/**
 * The authorization of an order request.
 * @export
 * @interface OrderAuthorizeRequest
 */
export interface OrderAuthorizeRequest {
    /**
     * 
     * @type {PaymentSource}
     * @memberof OrderAuthorizeRequest
     */
    'payment_source'?: PaymentSource;
}

