/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentMethod } from './payment-method';
import { StoredPaymentSource } from './stored-payment-source';

/**
 * Customizes the payer experience during the approval process for the payment with PayPal.<blockquote><strong>Note:</strong> Partners and Marketplaces might configure <code>brand_name</code> and <code>shipping_preference</code> during partner account setup, which overrides the request values.</blockquote>
 * @export
 * @interface OrderApplicationContext
 */
export interface OrderApplicationContext {
    /**
     * DEPRECATED. The label that overrides the business name in the PayPal account on the PayPal site. The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.brand_name`). Please specify this field in the `experience_context` object instead of the `application_context` object.
     * @type {string}
     * @memberof OrderApplicationContext
     */
    'brand_name'?: string;
    /**
     * The [language tag](https://tools.ietf.org/html/bcp47#section-2) for the language in which to localize the error-related strings, such as messages, issues, and suggested actions. The tag is made up of the [ISO 639-2 language code](https://www.loc.gov/standards/iso639-2/php/code_list.php), the optional [ISO-15924 script tag](https://www.unicode.org/iso15924/codelists.html), and the [ISO-3166 alpha-2 country code](https://raw.githubusercontent.com) or [M49 region code](https://unstats.un.org/unsd/methodology/m49/).
     * @type {string}
     * @memberof OrderApplicationContext
     */
    'locale'?: string;
    /**
     * DEPRECATED. DEPRECATED. The type of landing page to show on the PayPal site for customer checkout.  The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.landing_page`). Please specify this field in the `experience_context` object instead of the `application_context` object.
     * @type {string}
     * @memberof OrderApplicationContext
     * @deprecated
     */
    'landing_page'?: OrderApplicationContextLandingPageEnum;
    /**
     * DEPRECATED. DEPRECATED. The shipping preference:<ul><li>Displays the shipping address to the customer.</li><li>Enables the customer to choose an address on the PayPal site.</li><li>Restricts the customer from changing the address during the payment-approval process.</li></ul>.  The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.shipping_preference`). Please specify this field in the `experience_context` object instead of the `application_context` object.
     * @type {string}
     * @memberof OrderApplicationContext
     * @deprecated
     */
    'shipping_preference'?: OrderApplicationContextShippingPreferenceEnum;
    /**
     * DEPRECATED. Configures a <strong>Continue</strong> or <strong>Pay Now</strong> checkout flow.  The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.user_action`). Please specify this field in the `experience_context` object instead of the `application_context` object.
     * @type {string}
     * @memberof OrderApplicationContext
     */
    'user_action'?: OrderApplicationContextUserActionEnum;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof OrderApplicationContext
     */
    'payment_method'?: PaymentMethod;
    /**
     * DEPRECATED. The URL where the customer is redirected after the customer approves the payment. The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.return_url`). Please specify this field in the `experience_context` object instead of the `application_context` object.
     * @type {string}
     * @memberof OrderApplicationContext
     */
    'return_url'?: string;
    /**
     * DEPRECATED. The URL where the customer is redirected after the customer cancels the payment. The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.cancel_url`). Please specify this field in the `experience_context` object instead of the `application_context` object.
     * @type {string}
     * @memberof OrderApplicationContext
     */
    'cancel_url'?: string;
    /**
     * 
     * @type {StoredPaymentSource}
     * @memberof OrderApplicationContext
     */
    'stored_payment_source'?: StoredPaymentSource;
}

type OrderApplicationContextLandingPageEnum = 'LOGIN' | 'BILLING' | 'NO_PREFERENCE'
type OrderApplicationContextShippingPreferenceEnum = 'GET_FROM_FILE' | 'NO_SHIPPING' | 'SET_PROVIDED_ADDRESS'
type OrderApplicationContextUserActionEnum = 'CONTINUE' | 'PAY_NOW'


