/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error401 } from './error401';
import { ErrorLinkDescription } from './error-link-description';
import { Model401 } from './model401';
import { Model401DetailsInner } from './model401-details-inner';

/**
 * @type OrdersShowDetailsResponse
 * @export
 */
export type OrdersShowDetailsResponse = Error401 & Model401;


