/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error400 } from './error400';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersCapture400 } from './orders-capture400';
import { OrdersCapture400DetailsInner } from './orders-capture400-details-inner';

/**
 * @type OrdersCapturePaymentResponse
 * @export
 */
export type OrdersCapturePaymentResponse = Error400 & OrdersCapture400;


