/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERCOMPLETEDORVOIDED
 */
export interface ORDERCOMPLETEDORVOIDED {
    /**
     * 
     * @type {string}
     * @memberof ORDERCOMPLETEDORVOIDED
     */
    'description'?: ORDERCOMPLETEDORVOIDEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERCOMPLETEDORVOIDED
     */
    'issue'?: ORDERCOMPLETEDORVOIDEDIssueEnum;
}

type ORDERCOMPLETEDORVOIDEDDescriptionEnum = 'Order is voided or completed and hence cannot be authorized.'
type ORDERCOMPLETEDORVOIDEDIssueEnum = 'ORDER_COMPLETED_OR_VOIDED'


