/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersConfirm422DetailsInner } from './orders-confirm422-details-inner';

/**
 * 
 * @export
 * @interface OrdersConfirm422
 */
export interface OrdersConfirm422 {
    /**
     * 
     * @type {Array<OrdersConfirm422DetailsInner>}
     * @memberof OrdersConfirm422
     */
    'details'?: Array<OrdersConfirm422DetailsInner>;
}

