/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERISPENDINGAPPROVAL
 */
export interface ORDERISPENDINGAPPROVAL {
    /**
     * 
     * @type {string}
     * @memberof ORDERISPENDINGAPPROVAL
     */
    'description'?: ORDERISPENDINGAPPROVALDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERISPENDINGAPPROVAL
     */
    'issue'?: ORDERISPENDINGAPPROVALIssueEnum;
}

type ORDERISPENDINGAPPROVALDescriptionEnum = 'The order was confirmed and payer action completed but order approval processing from PayPal is pending. No action is needed from Payee or Payer. Please wait until order status changes to \'APPROVED\'.'
type ORDERISPENDINGAPPROVALIssueEnum = 'ORDER_IS_PENDING_APPROVAL'


