/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error422 } from './error422';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersConfirm422 } from './orders-confirm422';
import { OrdersConfirm422DetailsInner } from './orders-confirm422-details-inner';

/**
 * @type OrdersConfirmPaymentSource422Response
 * @export
 */
export type OrdersConfirmPaymentSource422Response = Error422 & OrdersConfirm422;


