/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersTrackCreate400DetailsInner } from './orders-track-create400-details-inner';

/**
 * 
 * @export
 * @interface OrdersTrackCreate400
 */
export interface OrdersTrackCreate400 {
    /**
     * 
     * @type {Array<OrdersTrackCreate400DetailsInner>}
     * @memberof OrdersTrackCreate400
     */
    'details'?: Array<OrdersTrackCreate400DetailsInner>;
}

