/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERCOMPLETIONINPROGRESS
 */
export interface ORDERCOMPLETIONINPROGRESS {
    /**
     * 
     * @type {string}
     * @memberof ORDERCOMPLETIONINPROGRESS
     */
    'description'?: ORDERCOMPLETIONINPROGRESSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERCOMPLETIONINPROGRESS
     */
    'issue'?: ORDERCOMPLETIONINPROGRESSIssueEnum;
}

type ORDERCOMPLETIONINPROGRESSDescriptionEnum = 'The order was created with processing_instruction of ORDER_COMPLETE_ON_PAYMENT_APPROVAL. The customer has approved the payment and PayPal is still in the process of capturing the order on your behalf as instructed. Please try your request again.'
type ORDERCOMPLETIONINPROGRESSIssueEnum = 'ORDER_COMPLETION_IN_PROGRESS'


