/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FIELDNOTPATCHABLE } from './fieldnotpatchable';
import { INVALIDPARAMETERVALUE1 } from './invalidparametervalue1';
import { INVALIDPATCHOPERATION } from './invalidpatchoperation';
import { INVALIDSTRINGLENGTH1 } from './invalidstringlength1';
import { MALFORMEDREQUESTJSON } from './malformedrequestjson';
import { MISSINGREQUIREDPARAMETER3 } from './missingrequiredparameter3';

/**
 * @type OrdersTrackersPatch400DetailsInner
 * @export
 */
export type OrdersTrackersPatch400DetailsInner = FIELDNOTPATCHABLE | INVALIDPARAMETERVALUE1 | MISSINGREQUIREDPARAMETER3 | INVALIDSTRINGLENGTH1 | INVALIDPATCHOPERATION | MALFORMEDREQUESTJSON;


