/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error422 } from './error422';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersPatch422 } from './orders-patch422';
import { OrdersPatch422DetailsInner } from './orders-patch422-details-inner';

/**
 * @type OrdersUpdateOrderStatus422Response
 * @export
 */
export type OrdersUpdateOrderStatus422Response = Error422 & OrdersPatch422;


