/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error403 } from './error403';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersCapture403 } from './orders-capture403';
import { OrdersCapture403DetailsInner } from './orders-capture403-details-inner';

/**
 * @type OrdersCapturePayment403Response
 * @export
 */
export type OrdersCapturePayment403Response = Error403 & OrdersCapture403;


