/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ORDERNOTAPPROVED1
 */
export interface ORDERNOTAPPROVED1 {
    /**
     * 
     * @type {string}
     * @memberof ORDERNOTAPPROVED1
     */
    'description'?: ORDERNOTAPPROVED1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof ORDERNOTAPPROVED1
     */
    'issue'?: ORDERNOTAPPROVED1IssueEnum;
}

type ORDERNOTAPPROVED1DescriptionEnum = 'Payer has not yet approved the Order for payment. Please redirect the payer to the \'rel\':\'approve\' url returned as part of the HATEOAS links within the Create Order call or provide a valid `payment_source` in the request.'
type ORDERNOTAPPROVED1IssueEnum = 'ORDER_NOT_APPROVED'


