/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutPaymentIntent } from './checkout-payment-intent';
import { OrderApplicationContext } from './order-application-context';
import { Payer } from './payer';
import { PaymentSource } from './payment-source';
import { PurchaseUnitRequest } from './purchase-unit-request';

/**
 * The order request details.
 * @export
 * @interface OrderRequest
 */
export interface OrderRequest {
    /**
     * The intent to either capture payment immediately or authorize a payment for an order after order creation.
     * @type {CheckoutPaymentIntent}
     * @memberof OrderRequest
     */
    'intent': CheckoutPaymentIntent;
    /**
     * 
     * @type {Payer}
     * @memberof OrderRequest
     */
    'payer'?: Payer;
    /**
     * An array of purchase units. Each purchase unit establishes a contract between a payer and the payee. Each purchase unit represents either a full or partial order that the payer intends to purchase from the payee.
     * @type {Array<PurchaseUnitRequest>}
     * @memberof OrderRequest
     */
    'purchase_units': Array<PurchaseUnitRequest>;
    /**
     * 
     * @type {PaymentSource}
     * @memberof OrderRequest
     */
    'payment_source'?: PaymentSource;
    /**
     * 
     * @type {OrderApplicationContext}
     * @memberof OrderRequest
     */
    'application_context'?: OrderApplicationContext;
}

