/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error404 } from './error404';
import { ErrorLinkDescription } from './error-link-description';
import { Model404 } from './model404';
import { Model404DetailsInner } from './model404-details-inner';

/**
 * @type OrdersAuthorizePaymentOrder404Response
 * @export
 */
export type OrdersAuthorizePaymentOrder404Response = Error404 & Model404;


