/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrderTrackerRequestAllOf } from './order-tracker-request-all-of';
import { ShipmentCarrier } from './shipment-carrier';
import { ShipmentTracker } from './shipment-tracker';
import { ShipmentTrackingNumberType } from './shipment-tracking-number-type';
import { ShipmentTrackingStatus } from './shipment-tracking-status';
import { TrackerItem } from './tracker-item';

/**
 * @type OrderTrackerRequest
 * The tracking details of an order.
 * @export
 */
export type OrderTrackerRequest = OrderTrackerRequestAllOf & ShipmentTracker;


