/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information used to pay using P24(Przelewy24).
 * @export
 * @interface P24
 */
export interface P24 {
    /**
     * The full name representation like Mr J Smith.
     * @type {string}
     * @memberof P24
     */
    'name'?: string;
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof P24
     */
    'email'?: string;
    /**
     * The [two-character ISO 3166-1 code](https://raw.githubusercontent.com) that identifies the country or region.<blockquote><strong>Note:</strong> The country code for Great Britain is <code>GB</code> and not <code>UK</code> as used in the top-level domain names for that country. Use the `C2` country code for China worldwide for comparable uncontrolled price (CUP) method, bank card, and cross-border transactions.</blockquote>
     * @type {string}
     * @memberof P24
     */
    'country_code'?: string;
    /**
     * P24 generated payment description.
     * @type {string}
     * @memberof P24
     */
    'payment_descriptor'?: string;
    /**
     * Numeric identifier of the payment scheme or bank used for the payment.
     * @type {string}
     * @memberof P24
     */
    'method_id'?: string;
    /**
     * Friendly name of the payment scheme or bank used for the payment.
     * @type {string}
     * @memberof P24
     */
    'method_description'?: string;
}

