/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Transactions status result identifier. The outcome of the issuer\'s authentication.
 * @export
 * @enum {string}
 */
export type ParesStatus = 'Y' | 'N' | 'U' | 'A' | 'C' | 'R' | 'D' | 'I'

