/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PATCHVALUEREQUIRED
 */
export interface PATCHVALUEREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof PATCHVALUEREQUIRED
     */
    'description'?: PATCHVALUEREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PATCHVALUEREQUIRED
     */
    'issue'?: PATCHVALUEREQUIREDIssueEnum;
}

type PATCHVALUEREQUIREDDescriptionEnum = 'Please specify a \'value\' to for the field that is being patched.'
type PATCHVALUEREQUIREDIssueEnum = 'PATCH_VALUE_REQUIRED'


