/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The JSON patch object to apply partial updates to resources.
 * @export
 * @interface Patch
 */
export interface Patch {
    /**
     * The operation.
     * @type {string}
     * @memberof Patch
     */
    'op': PatchOpEnum;
    /**
     * The <a href=\"https://tools.ietf.org/html/rfc6901\">JSON Pointer</a> to the target document location at which to complete the operation.
     * @type {string}
     * @memberof Patch
     */
    'path'?: string;
    /**
     * The value to apply. The <code>remove</code>, <code>copy</code>, and <code>move</code> operations do not require a value. Since <a href=\"https://www.rfc-editor.org/rfc/rfc69021\">JSON Patch</a> allows any type for <code>value</code>, the <code>type</code> property is not specified.
     * @type {any}
     * @memberof Patch
     */
    'value'?: any;
    /**
     * The <a href=\"https://tools.ietf.org/html/rfc6901\">JSON Pointer</a> to the target document location from which to move the value. Required for the <code>move</code> operation.
     * @type {string}
     * @memberof Patch
     */
    'from'?: string;
}

type PatchOpEnum = 'add' | 'remove' | 'replace' | 'move' | 'copy' | 'test'


