/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PATCHPATHREQUIRED
 */
export interface PATCHPATHREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof PATCHPATHREQUIRED
     */
    'description'?: PATCHPATHREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PATCHPATHREQUIRED
     */
    'issue'?: PATCHPATHREQUIREDIssueEnum;
}

type PATCHPATHREQUIREDDescriptionEnum = 'Please specify a \'path\' for the field for which the operation needs to be performed.'
type PATCHPATHREQUIREDIssueEnum = 'PATCH_PATH_REQUIRED'


