/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PATCHPATHREQUIRED1
 */
export interface PATCHPATHREQUIRED1 {
    /**
     * 
     * @type {string}
     * @memberof PATCHPATHREQUIRED1
     */
    'description'?: PATCHPATHREQUIRED1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PATCHPATHREQUIRED1
     */
    'issue'?: PATCHPATHREQUIRED1IssueEnum;
}

type PATCHPATHREQUIRED1DescriptionEnum = 'Specify a `value` for the field in which the operation needs to be performed.'
type PATCHPATHREQUIRED1IssueEnum = 'PATCH_PATH_REQUIRED'


