/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEENOTENABLEDFORCARDPROCESSING
 */
export interface PAYEENOTENABLEDFORCARDPROCESSING {
    /**
     * 
     * @type {string}
     * @memberof PAYEENOTENABLEDFORCARDPROCESSING
     */
    'description'?: PAYEENOTENABLEDFORCARDPROCESSINGDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEENOTENABLEDFORCARDPROCESSING
     */
    'issue'?: PAYEENOTENABLEDFORCARDPROCESSINGIssueEnum;
}

type PAYEENOTENABLEDFORCARDPROCESSINGDescriptionEnum = 'Payee account is not setup to be able to process card payments. Please contact PayPal customer support.'
type PAYEENOTENABLEDFORCARDPROCESSINGIssueEnum = 'PAYEE_NOT_ENABLED_FOR_CARD_PROCESSING'


