/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEFXRATEIDEXPIRED
 */
export interface PAYEEFXRATEIDEXPIRED {
    /**
     * 
     * @type {string}
     * @memberof PAYEEFXRATEIDEXPIRED
     */
    'description'?: PAYEEFXRATEIDEXPIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEFXRATEIDEXPIRED
     */
    'issue'?: PAYEEFXRATEIDEXPIREDIssueEnum;
}

type PAYEEFXRATEIDEXPIREDDescriptionEnum = 'The specified FX Rate ID has expired. Please specify a different FX Rate Id and try the request again. Alternately, remove the FX Rate ID to process the request using the default exchange rate.'
type PAYEEFXRATEIDEXPIREDIssueEnum = 'PAYEE_FX_RATE_ID_EXPIRED'


