/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYERCANNOTPAY1
 */
export interface PAYERCANNOTPAY1 {
    /**
     * 
     * @type {string}
     * @memberof PAYERCANNOTPAY1
     */
    'description'?: PAYERCANNOTPAY1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYERCANNOTPAY1
     */
    'issue'?: PAYERCANNOTPAY1IssueEnum;
}

type PAYERCANNOTPAY1DescriptionEnum = 'Payer cannot pay for this transaction. Please contact the payer to find other ways to pay for this transaction.'
type PAYERCANNOTPAY1IssueEnum = 'PAYER_CANNOT_PAY'


