/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYERACCOUNTRESTRICTED
 */
export interface PAYERACCOUNTRESTRICTED {
    /**
     * 
     * @type {string}
     * @memberof PAYERACCOUNTRESTRICTED
     */
    'description'?: PAYERACCOUNTRESTRICTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYERACCOUNTRESTRICTED
     */
    'issue'?: PAYERACCOUNTRESTRICTEDIssueEnum;
}

type PAYERACCOUNTRESTRICTEDDescriptionEnum = 'PAYER_ACCOUNT_RESTRICTED'
type PAYERACCOUNTRESTRICTEDIssueEnum = 'PAYER_ACCOUNT_RESTRICTED'


