/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEACCOUNTNOTVERIFIED
 */
export interface PAYEEACCOUNTNOTVERIFIED {
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTNOTVERIFIED
     */
    'description'?: PAYEEACCOUNTNOTVERIFIEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTNOTVERIFIED
     */
    'issue'?: PAYEEACCOUNTNOTVERIFIEDIssueEnum;
}

type PAYEEACCOUNTNOTVERIFIEDDescriptionEnum = 'Payee has not verified their account with PayPal. The selected payment method requires the recipient to have a verified PayPal account before transactions can be processed on their behalf.'
type PAYEEACCOUNTNOTVERIFIEDIssueEnum = 'PAYEE_ACCOUNT_NOT_VERIFIED'


