/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEACCOUNTINVALID
 */
export interface PAYEEACCOUNTINVALID {
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTINVALID
     */
    'description'?: PAYEEACCOUNTINVALIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTINVALID
     */
    'issue'?: PAYEEACCOUNTINVALIDIssueEnum;
}

type PAYEEACCOUNTINVALIDDescriptionEnum = 'Payee account specified is invalid. Please check the `payee.email_address` or `payee.merchant_id` specified and try again. Ensure that either  `payee.merchant_id` or `payee.email_address` is specified.'
type PAYEEACCOUNTINVALIDIssueEnum = 'PAYEE_ACCOUNT_INVALID'


