/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCE
 */
export interface PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCE {
    /**
     * 
     * @type {string}
     * @memberof PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCE
     */
    'description'?: PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCE
     */
    'issue'?: PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCEIssueEnum;
}

type PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCEDescriptionEnum = 'Payee country code is not supported by the provided payment source.'
type PAYEECOUNTRYNOTSUPPORTEDFORPAYMENTSOURCEIssueEnum = 'PAYEE_COUNTRY_NOT_SUPPORTED_FOR_PAYMENT_SOURCE'


