/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEPRICINGTIERIDNOTENABLED
 */
export interface PAYEEPRICINGTIERIDNOTENABLED {
    /**
     * 
     * @type {string}
     * @memberof PAYEEPRICINGTIERIDNOTENABLED
     */
    'description'?: PAYEEPRICINGTIERIDNOTENABLEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEPRICINGTIERIDNOTENABLED
     */
    'issue'?: PAYEEPRICINGTIERIDNOTENABLEDIssueEnum;
}

type PAYEEPRICINGTIERIDNOTENABLEDDescriptionEnum = 'The API Caller is not enabled to process transactions by specifying a \'payee_pricing_tier_id\'. Please work with your Account Manager to enable this option for your account.'
type PAYEEPRICINGTIERIDNOTENABLEDIssueEnum = 'PAYEE_PRICING_TIER_ID_NOT_ENABLED'


