/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressPortable } from './address-portable';
import { Name } from './name';
import { PayerAllOf } from './payer-all-of';
import { PayerBase } from './payer-base';
import { PhoneWithType } from './phone-with-type';
import { TaxInfo } from './tax-info';

/**
 * @type Payer
 * The customer who approves and pays for the order. The customer is also known as the payer.
 * @export
 */
export type Payer = PayerAllOf & PayerBase;


