/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressPortable } from './address-portable';
import { Name } from './name';
import { PhoneWithType } from './phone-with-type';
import { TaxInfo } from './tax-info';

/**
 * 
 * @export
 * @interface PayerAllOf
 */
export interface PayerAllOf {
    /**
     * 
     * @type {Name}
     * @memberof PayerAllOf
     */
    'name'?: Name;
    /**
     * 
     * @type {PhoneWithType}
     * @memberof PayerAllOf
     */
    'phone'?: PhoneWithType;
    /**
     * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
     * @type {string}
     * @memberof PayerAllOf
     */
    'birth_date'?: string;
    /**
     * 
     * @type {TaxInfo}
     * @memberof PayerAllOf
     */
    'tax_info'?: TaxInfo;
    /**
     * 
     * @type {AddressPortable}
     * @memberof PayerAllOf
     */
    'address'?: AddressPortable;
}

