/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEENOTENABLEDFORBANKPROCESSING
 */
export interface PAYEENOTENABLEDFORBANKPROCESSING {
    /**
     * 
     * @type {string}
     * @memberof PAYEENOTENABLEDFORBANKPROCESSING
     */
    'description'?: PAYEENOTENABLEDFORBANKPROCESSINGDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEENOTENABLEDFORBANKPROCESSING
     */
    'issue'?: PAYEENOTENABLEDFORBANKPROCESSINGIssueEnum;
}

type PAYEENOTENABLEDFORBANKPROCESSINGDescriptionEnum = 'Payee account is not setup to be able to process bank payments. Please contact your PayPal account manager.'
type PAYEENOTENABLEDFORBANKPROCESSINGIssueEnum = 'PAYEE_NOT_ENABLED_FOR_BANK_PROCESSING'


