/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEACCOUNTRESTRICTED
 */
export interface PAYEEACCOUNTRESTRICTED {
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTRESTRICTED
     */
    'description'?: PAYEEACCOUNTRESTRICTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTRESTRICTED
     */
    'issue'?: PAYEEACCOUNTRESTRICTEDIssueEnum;
}

type PAYEEACCOUNTRESTRICTEDDescriptionEnum = 'The merchant account is restricted.'
type PAYEEACCOUNTRESTRICTEDIssueEnum = 'PAYEE_ACCOUNT_RESTRICTED'


