/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYERCANNOTPAY
 */
export interface PAYERCANNOTPAY {
    /**
     * 
     * @type {string}
     * @memberof PAYERCANNOTPAY
     */
    'description'?: PAYERCANNOTPAYDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYERCANNOTPAY
     */
    'issue'?: PAYERCANNOTPAYIssueEnum;
}

type PAYERCANNOTPAYDescriptionEnum = 'Combination of payer and payee settings mean that this buyer cannot pay this seller.'
type PAYERCANNOTPAYIssueEnum = 'PAYER_CANNOT_PAY'


