/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEFXRATEIDCURRENCYMISMATCH
 */
export interface PAYEEFXRATEIDCURRENCYMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof PAYEEFXRATEIDCURRENCYMISMATCH
     */
    'description'?: PAYEEFXRATEIDCURRENCYMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEFXRATEIDCURRENCYMISMATCH
     */
    'issue'?: PAYEEFXRATEIDCURRENCYMISMATCHIssueEnum;
}

type PAYEEFXRATEIDCURRENCYMISMATCHDescriptionEnum = 'The specified FX Rate ID is for a currency that does not match with the currency of this request. Please specify a different FX Rate ID and try the request again. Alternately, remove the FX Rate ID to process the request using the default exchange rate.'
type PAYEEFXRATEIDCURRENCYMISMATCHIssueEnum = 'PAYEE_FX_RATE_ID_CURRENCY_MISMATCH'


