/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEBLOCKEDTRANSACTION
 */
export interface PAYEEBLOCKEDTRANSACTION {
    /**
     * 
     * @type {string}
     * @memberof PAYEEBLOCKEDTRANSACTION
     */
    'description'?: PAYEEBLOCKEDTRANSACTIONDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEBLOCKEDTRANSACTION
     */
    'issue'?: PAYEEBLOCKEDTRANSACTIONIssueEnum;
}

type PAYEEBLOCKEDTRANSACTIONDescriptionEnum = 'The Fraud settings for this seller are such that this payment cannot be executed.'
type PAYEEBLOCKEDTRANSACTIONIssueEnum = 'PAYEE_BLOCKED_TRANSACTION'


