/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYMENTSOURCEINFOCANNOTBEVERIFIED
 */
export interface PAYMENTSOURCEINFOCANNOTBEVERIFIED {
    /**
     * 
     * @type {string}
     * @memberof PAYMENTSOURCEINFOCANNOTBEVERIFIED
     */
    'description'?: PAYMENTSOURCEINFOCANNOTBEVERIFIEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYMENTSOURCEINFOCANNOTBEVERIFIED
     */
    'issue'?: PAYMENTSOURCEINFOCANNOTBEVERIFIEDIssueEnum;
}

type PAYMENTSOURCEINFOCANNOTBEVERIFIEDDescriptionEnum = 'The combination of the payment_source name, billing address, shipping name and shipping address could not be verified. Please correct this information and try again by creating a new order.'
type PAYMENTSOURCEINFOCANNOTBEVERIFIEDIssueEnum = 'PAYMENT_SOURCE_INFO_CANNOT_BE_VERIFIED'


