/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYMENTALREADYAPPROVED
 */
export interface PAYMENTALREADYAPPROVED {
    /**
     * 
     * @type {string}
     * @memberof PAYMENTALREADYAPPROVED
     */
    'description'?: PAYMENTALREADYAPPROVEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYMENTALREADYAPPROVED
     */
    'issue'?: PAYMENTALREADYAPPROVEDIssueEnum;
}

type PAYMENTALREADYAPPROVEDDescriptionEnum = 'The payment has already been approved.  Please capture the order, or create and confirm a new order with this payment source.'
type PAYMENTALREADYAPPROVEDIssueEnum = 'PAYMENT_ALREADY_APPROVED'


