/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthorizationWithAdditionalData } from './authorization-with-additional-data';
import { Capture } from './capture';
import { Refund } from './refund';

/**
 * The collection of payments, or transactions, for a purchase unit in an order. For example, authorized payments, captured payments, and refunds.
 * @export
 * @interface PaymentCollection
 */
export interface PaymentCollection {
    /**
     * An array of authorized payments for a purchase unit. A purchase unit can have zero or more authorized payments.
     * @type {Array<AuthorizationWithAdditionalData>}
     * @memberof PaymentCollection
     */
    'authorizations'?: Array<AuthorizationWithAdditionalData>;
    /**
     * An array of captured payments for a purchase unit. A purchase unit can have zero or more captured payments.
     * @type {Array<Capture>}
     * @memberof PaymentCollection
     */
    'captures'?: Array<Capture>;
    /**
     * An array of refunds for a purchase unit. A purchase unit can have zero or more refunds.
     * @type {Array<Refund>}
     * @memberof PaymentCollection
     */
    'refunds'?: Array<Refund>;
}

