/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayeePaymentMethodPreference } from './payee-payment-method-preference';

/**
 * The customer and merchant payment preferences.
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
    /**
     * The merchant-preferred payment methods.
     * @type {PayeePaymentMethodPreference}
     * @memberof PaymentMethod
     */
    'payee_preferred'?: PayeePaymentMethodPreference;
    /**
     * NACHA (the regulatory body governing the ACH network) requires that API callers (merchants, partners) obtain the consumer’s explicit authorization before initiating a transaction. To stay compliant, you’ll need to make sure that you retain a compliant authorization for each transaction that you originate to the ACH Network using this API. ACH transactions are categorized (using SEC codes) by how you capture authorization from the Receiver (the person whose bank account is being debited or credited). PayPal supports the following SEC codes.
     * @type {string}
     * @memberof PaymentMethod
     */
    'standard_entry_class_code'?: PaymentMethodStandardEntryClassCodeEnum;
}

type PaymentMethodStandardEntryClassCodeEnum = 'TEL' | 'WEB' | 'CCD' | 'PPD'


