/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYMENTSOURCEMISMATCH
 */
export interface PAYMENTSOURCEMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof PAYMENTSOURCEMISMATCH
     */
    'description'?: PAYMENTSOURCEMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYMENTSOURCEMISMATCH
     */
    'issue'?: PAYMENTSOURCEMISMATCHIssueEnum;
}

type PAYMENTSOURCEMISMATCHDescriptionEnum = 'The `payment_source` in the request must match the `payment_source` used for the authorization or capture referenced by `previous_transaction_reference`. Please use `previous_transaction_reference` whose `payment_source` matches with the `payment_source` specified in the order.'
type PAYMENTSOURCEMISMATCHIssueEnum = 'PAYMENT_SOURCE_MISMATCH'


