/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYMENTTYPENOTSUPPORTEDFORINTENT
 */
export interface PAYMENTTYPENOTSUPPORTEDFORINTENT {
    /**
     * 
     * @type {string}
     * @memberof PAYMENTTYPENOTSUPPORTEDFORINTENT
     */
    'description'?: PAYMENTTYPENOTSUPPORTEDFORINTENTDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYMENTTYPENOTSUPPORTEDFORINTENT
     */
    'issue'?: PAYMENTTYPENOTSUPPORTEDFORINTENTIssueEnum;
}

type PAYMENTTYPENOTSUPPORTEDFORINTENTDescriptionEnum = 'Provided payment type not supported for order intent. Payment authorizations are supported only for order with `intent=AUTHORIZE` and payment captures are supported only for order with `intent=CAPTURE`.'
type PAYMENTTYPENOTSUPPORTEDFORINTENTIssueEnum = 'PAYMENT_TYPE_NOT_SUPPORTED_FOR_INTENT'


