/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressPortable2 } from './address-portable2';
import { Name2 } from './name2';
import { PaypalWalletAttributes } from './paypal-wallet-attributes';
import { PaypalWalletExperienceContext } from './paypal-wallet-experience-context';
import { PhoneWithType } from './phone-with-type';
import { TaxInfo } from './tax-info';

/**
 * A resource that identifies a PayPal Wallet is used for payment.
 * @export
 * @interface PaypalWallet
 */
export interface PaypalWallet {
    /**
     * The PayPal-generated ID for the vaulted payment source. This ID should be stored on the merchant\'s server so the saved payment source can be used for future transactions.
     * @type {string}
     * @memberof PaypalWallet
     */
    'vault_id'?: string;
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof PaypalWallet
     */
    'email_address'?: string;
    /**
     * 
     * @type {Name2}
     * @memberof PaypalWallet
     */
    'name'?: Name2;
    /**
     * 
     * @type {PhoneWithType}
     * @memberof PaypalWallet
     */
    'phone'?: PhoneWithType;
    /**
     * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
     * @type {string}
     * @memberof PaypalWallet
     */
    'birth_date'?: string;
    /**
     * 
     * @type {TaxInfo}
     * @memberof PaypalWallet
     */
    'tax_info'?: TaxInfo;
    /**
     * 
     * @type {AddressPortable2}
     * @memberof PaypalWallet
     */
    'address'?: AddressPortable2;
    /**
     * 
     * @type {PaypalWalletAttributes}
     * @memberof PaypalWallet
     */
    'attributes'?: PaypalWalletAttributes;
    /**
     * 
     * @type {PaypalWalletExperienceContext}
     * @memberof PaypalWallet
     */
    'experience_context'?: PaypalWalletExperienceContext;
    /**
     * The PayPal billing agreement ID. References an approved recurring payment for goods or services.
     * @type {string}
     * @memberof PaypalWallet
     */
    'billing_agreement_id'?: string;
}

