/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CobrandedCard } from './cobranded-card';
import { PaypalWalletVaultResponse } from './paypal-wallet-vault-response';

/**
 * Additional attributes associated with the use of a PayPal Wallet.
 * @export
 * @interface PaypalWalletAttributesResponse
 */
export interface PaypalWalletAttributesResponse {
    /**
     * 
     * @type {PaypalWalletVaultResponse}
     * @memberof PaypalWalletAttributesResponse
     */
    'vault'?: PaypalWalletVaultResponse;
    /**
     * An array of merchant cobranded cards used by buyer to complete an order. This array will be present if a merchant has onboarded their cobranded card with PayPal and provided corresponding label(s).
     * @type {Array<CobrandedCard>}
     * @memberof PaypalWalletAttributesResponse
     */
    'cobranded_cards'?: Array<CobrandedCard>;
}

