/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressPortable2 } from './address-portable2';
import { Name2 } from './name2';
import { PaypalWalletAttributesResponse } from './paypal-wallet-attributes-response';
import { Phone2 } from './phone2';
import { PhoneType2 } from './phone-type2';
import { TaxInfo } from './tax-info';

/**
 * The PayPal Wallet response.
 * @export
 * @interface PaypalWalletResponse
 */
export interface PaypalWalletResponse {
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof PaypalWalletResponse
     */
    'email_address'?: string;
    /**
     * The PayPal payer ID, which is a masked version of the PayPal account number intended for use with third parties. The account number is reversibly encrypted and a proprietary variant of Base32 is used to encode the result.
     * @type {string}
     * @memberof PaypalWalletResponse
     */
    'account_id'?: string;
    /**
     * The account status indicates whether the buyer has verified the financial details associated with their PayPal account.
     * @type {string}
     * @memberof PaypalWalletResponse
     */
    'account_status'?: PaypalWalletResponseAccountStatusEnum;
    /**
     * 
     * @type {Name2}
     * @memberof PaypalWalletResponse
     */
    'name'?: Name2;
    /**
     * The phone type.
     * @type {PhoneType2}
     * @memberof PaypalWalletResponse
     */
    'phone_type'?: PhoneType2;
    /**
     * 
     * @type {Phone2}
     * @memberof PaypalWalletResponse
     */
    'phone_number'?: Phone2;
    /**
     * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
     * @type {string}
     * @memberof PaypalWalletResponse
     */
    'birth_date'?: string;
    /**
     * 
     * @type {TaxInfo}
     * @memberof PaypalWalletResponse
     */
    'tax_info'?: TaxInfo;
    /**
     * 
     * @type {AddressPortable2}
     * @memberof PaypalWalletResponse
     */
    'address'?: AddressPortable2;
    /**
     * 
     * @type {PaypalWalletAttributesResponse}
     * @memberof PaypalWalletResponse
     */
    'attributes'?: PaypalWalletAttributesResponse;
}

type PaypalWalletResponseAccountStatusEnum = 'VERIFIED' | 'UNVERIFIED'


