/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYPALTRANSACTIONIDEXPIRED
 */
export interface PAYPALTRANSACTIONIDEXPIRED {
    /**
     * 
     * @type {string}
     * @memberof PAYPALTRANSACTIONIDEXPIRED
     */
    'description'?: PAYPALTRANSACTIONIDEXPIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYPALTRANSACTIONIDEXPIRED
     */
    'issue'?: PAYPALTRANSACTIONIDEXPIREDIssueEnum;
}

type PAYPALTRANSACTIONIDEXPIREDDescriptionEnum = 'Specified `paypal_transaction_id` has expired. PayPal transaction ID expires 4 years after the date of the initial transaction.'
type PAYPALTRANSACTIONIDEXPIREDIssueEnum = 'PAYPAL_TRANSACTION_ID_EXPIRED'


