/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYPALTRANSACTIONIDNOTFOUND
 */
export interface PAYPALTRANSACTIONIDNOTFOUND {
    /**
     * 
     * @type {string}
     * @memberof PAYPALTRANSACTIONIDNOTFOUND
     */
    'description'?: PAYPALTRANSACTIONIDNOTFOUNDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYPALTRANSACTIONIDNOTFOUND
     */
    'issue'?: PAYPALTRANSACTIONIDNOTFOUNDIssueEnum;
}

type PAYPALTRANSACTIONIDNOTFOUNDDescriptionEnum = 'Specified `paypal_transaction_id` was not found. Verify the value and try the request again.'
type PAYPALTRANSACTIONIDNOTFOUNDIssueEnum = 'PAYPAL_TRANSACTION_ID_NOT_FOUND'


