/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LinkDescription } from './link-description';
import { PaypalWalletCustomer } from './paypal-wallet-customer';
import { PaypalWalletVaultResponseAllOf } from './paypal-wallet-vault-response-all-of';
import { VaultResponse } from './vault-response';

/**
 * @type PaypalWalletVaultResponse
 * The details about a saved PayPal Wallet payment source.
 * @export
 */
export type PaypalWalletVaultResponse = PaypalWalletVaultResponseAllOf & VaultResponse;


