/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PERMISSIONDENIEDFORDONATIONITEMS
 */
export interface PERMISSIONDENIEDFORDONATIONITEMS {
    /**
     * 
     * @type {string}
     * @memberof PERMISSIONDENIEDFORDONATIONITEMS
     */
    'description'?: PERMISSIONDENIEDFORDONATIONITEMSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PERMISSIONDENIEDFORDONATIONITEMS
     */
    'issue'?: PERMISSIONDENIEDFORDONATIONITEMSIssueEnum;
}

type PERMISSIONDENIEDFORDONATIONITEMSDescriptionEnum = 'The API Caller or Payee have not been granted appropriate permissions to send \'items.category\' as \'DONATION\'. Please speak to your account manager if you want to process these type of items.'
type PERMISSIONDENIEDFORDONATIONITEMSIssueEnum = 'PERMISSION_DENIED_FOR_DONATION_ITEMS'


