/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PLATFORMFEEPAYEECANNOTBESAMEASPAYER
 */
export interface PLATFORMFEEPAYEECANNOTBESAMEASPAYER {
    /**
     * 
     * @type {string}
     * @memberof PLATFORMFEEPAYEECANNOTBESAMEASPAYER
     */
    'description'?: PLATFORMFEEPAYEECANNOTBESAMEASPAYERDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PLATFORMFEEPAYEECANNOTBESAMEASPAYER
     */
    'issue'?: PLATFORMFEEPAYEECANNOTBESAMEASPAYERIssueEnum;
}

type PLATFORMFEEPAYEECANNOTBESAMEASPAYERDescriptionEnum = 'The payer cannot pay themselves. The recipient account of the platform fees must be different from the payer account.'
type PLATFORMFEEPAYEECANNOTBESAMEASPAYERIssueEnum = 'PLATFORM_FEE_PAYEE_CANNOT_BE_SAME_AS_PAYER'


