/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PLATFORMFEESNOTSUPPORTED
 */
export interface PLATFORMFEESNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof PLATFORMFEESNOTSUPPORTED
     */
    'description'?: PLATFORMFEESNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PLATFORMFEESNOTSUPPORTED
     */
    'issue'?: PLATFORMFEESNOTSUPPORTEDIssueEnum;
}

type PLATFORMFEESNOTSUPPORTEDDescriptionEnum = 'The API Caller is not enabled to process transactions by specifying \'platform_fees\'. Please work with your PayPal Account Manager to enable this option for your account.'
type PLATFORMFEESNOTSUPPORTEDIssueEnum = 'PLATFORM_FEES_NOT_SUPPORTED'


