/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PNREFEXPIRED
 */
export interface PNREFEXPIRED {
    /**
     * 
     * @type {string}
     * @memberof PNREFEXPIRED
     */
    'description'?: PNREFEXPIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PNREFEXPIRED
     */
    'issue'?: PNREFEXPIREDIssueEnum;
}

type PNREFEXPIREDDescriptionEnum = 'Specified `pnref` has expired. PNREF expires 15 months after the date of the initial transaction.'
type PNREFEXPIREDIssueEnum = 'PNREF_EXPIRED'


