/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface POSTALCODEREQUIRED
 */
export interface POSTALCODEREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof POSTALCODEREQUIRED
     */
    'description'?: POSTALCODEREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof POSTALCODEREQUIRED
     */
    'issue'?: POSTALCODEREQUIREDIssueEnum;
}

type POSTALCODEREQUIREDDescriptionEnum = 'The specified country requires a postal code.'
type POSTALCODEREQUIREDIssueEnum = 'POSTAL_CODE_REQUIRED'


