/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PREFERREDPAYMENTSOURCEMISMATCH
 */
export interface PREFERREDPAYMENTSOURCEMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof PREFERREDPAYMENTSOURCEMISMATCH
     */
    'description'?: PREFERREDPAYMENTSOURCEMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PREFERREDPAYMENTSOURCEMISMATCH
     */
    'issue'?: PREFERREDPAYMENTSOURCEMISMATCHIssueEnum;
}

type PREFERREDPAYMENTSOURCEMISMATCHDescriptionEnum = 'Payment Source must exactly match the Preferred Payment Source that was provided during order creation.'
type PREFERREDPAYMENTSOURCEMISMATCHIssueEnum = 'PREFERRED_PAYMENT_SOURCE_MISMATCH'


