/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AmountWithBreakdown } from './amount-with-breakdown';
import { Item } from './item';
import { Payee } from './payee';
import { PaymentCollection } from './payment-collection';
import { PaymentInstruction } from './payment-instruction';
import { ShippingWithTrackingDetails } from './shipping-with-tracking-details';
import { SupplementaryData } from './supplementary-data';

/**
 * The purchase unit details. Used to capture required information for the payment contract.
 * @export
 * @interface PurchaseUnit
 */
export interface PurchaseUnit {
    /**
     * The purchase description.
     * @type {string}
     * @memberof PurchaseUnit
     */
    'description'?: string;
    /**
     * The API caller-provided external ID for the purchase unit. Required for multiple purchase units when you must update the order through `PATCH`. If you omit this value and the order contains only one purchase unit, PayPal sets this value to `default`. <blockquote><strong>Note:</strong> If there are multiple purchase units, <code>reference_id</code> is required for each purchase unit.</blockquote>
     * @type {string}
     * @memberof PurchaseUnit
     */
    'reference_id'?: string;
    /**
     * 
     * @type {AmountWithBreakdown}
     * @memberof PurchaseUnit
     */
    'amount'?: AmountWithBreakdown;
    /**
     * 
     * @type {Payee}
     * @memberof PurchaseUnit
     */
    'payee'?: Payee;
    /**
     * 
     * @type {PaymentInstruction}
     * @memberof PurchaseUnit
     */
    'payment_instruction'?: PaymentInstruction;
    /**
     * The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports.
     * @type {string}
     * @memberof PurchaseUnit
     */
    'custom_id'?: string;
    /**
     * The API caller-provided external invoice ID for this order.
     * @type {string}
     * @memberof PurchaseUnit
     */
    'invoice_id'?: string;
    /**
     * The PayPal-generated ID for the purchase unit. This ID appears in both the payer\'s transaction history and the emails that the payer receives. In addition, this ID is available in transaction and settlement reports that merchants and API callers can use to reconcile transactions. This ID is only available when an order is saved by calling <code>v2/checkout/orders/id/save</code>.
     * @type {string}
     * @memberof PurchaseUnit
     */
    'id'?: string;
    /**
     * The payment descriptor on account transactions on the customer\'s credit card statement, that PayPal sends to processors. The maximum length of the soft descriptor information that you can pass in the API field is 22 characters, in the following format:<code>22 - len(PAYPAL * (8)) - len(<var>Descriptor in Payment Receiving Preferences of Merchant account</var> + 1)</code>The PAYPAL prefix uses 8 characters.<br/><br/>The soft descriptor supports the following ASCII characters:<ul><li>Alphanumeric characters</li><li>Dashes</li><li>Asterisks</li><li>Periods (.)</li><li>Spaces</li></ul>For Wallet payments marketplace integrations:<ul><li>The merchant descriptor in the Payment Receiving Preferences must be the marketplace name.</li><li>You can\'t use the remaining space to show the customer service number.</li><li>The remaining spaces can be a combination of seller name and country.</li></ul><br/>For unbranded payments (Direct Card) marketplace integrations, use a combination of the seller name and phone number.
     * @type {string}
     * @memberof PurchaseUnit
     */
    'soft_descriptor'?: string;
    /**
     * An array of items that the customer purchases from the merchant.
     * @type {Array<Item>}
     * @memberof PurchaseUnit
     */
    'items'?: Array<Item>;
    /**
     * 
     * @type {ShippingWithTrackingDetails}
     * @memberof PurchaseUnit
     */
    'shipping'?: ShippingWithTrackingDetails;
    /**
     * 
     * @type {SupplementaryData}
     * @memberof PurchaseUnit
     */
    'supplementary_data'?: SupplementaryData;
    /**
     * 
     * @type {PaymentCollection}
     * @memberof PurchaseUnit
     */
    'payments'?: PaymentCollection;
}

