/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REDIRECTPAYERFORALTERNATEFUNDING
 */
export interface REDIRECTPAYERFORALTERNATEFUNDING {
    /**
     * 
     * @type {string}
     * @memberof REDIRECTPAYERFORALTERNATEFUNDING
     */
    'description'?: REDIRECTPAYERFORALTERNATEFUNDINGDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REDIRECTPAYERFORALTERNATEFUNDING
     */
    'issue'?: REDIRECTPAYERFORALTERNATEFUNDINGIssueEnum;
}

type REDIRECTPAYERFORALTERNATEFUNDINGDescriptionEnum = 'Transaction failed. Redirect the payer to select another funding source.'
type REDIRECTPAYERFORALTERNATEFUNDINGIssueEnum = 'REDIRECT_PAYER_FOR_ALTERNATE_FUNDING'


