/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REFERENCEDCARDEXPIRED
 */
export interface REFERENCEDCARDEXPIRED {
    /**
     * 
     * @type {string}
     * @memberof REFERENCEDCARDEXPIRED
     */
    'description'?: REFERENCEDCARDEXPIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REFERENCEDCARDEXPIRED
     */
    'issue'?: REFERENCEDCARDEXPIREDIssueEnum;
}

type REFERENCEDCARDEXPIREDDescriptionEnum = 'The card underlying the token has expired and hence cannot be used to process a payment.'
type REFERENCEDCARDEXPIREDIssueEnum = 'REFERENCED_CARD_EXPIRED'


