/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REFERENCEIDNOTFOUND
 */
export interface REFERENCEIDNOTFOUND {
    /**
     * 
     * @type {string}
     * @memberof REFERENCEIDNOTFOUND
     */
    'description'?: REFERENCEIDNOTFOUNDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REFERENCEIDNOTFOUND
     */
    'issue'?: REFERENCEIDNOTFOUNDIssueEnum;
}

type REFERENCEIDNOTFOUNDDescriptionEnum = 'Filter expression value is incorrect. Please check the value of the reference_id and try again.'
type REFERENCEIDNOTFOUNDIssueEnum = 'REFERENCE_ID_NOT_FOUND'


