/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REFERENCEIDREQUIRED
 */
export interface REFERENCEIDREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof REFERENCEIDREQUIRED
     */
    'description'?: REFERENCEIDREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REFERENCEIDREQUIRED
     */
    'issue'?: REFERENCEIDREQUIREDIssueEnum;
}

type REFERENCEIDREQUIREDDescriptionEnum = '\'reference_id\' is required for each \'purchase_unit\' if multiple \'purchase_unit\' are provided.'
type REFERENCEIDREQUIREDIssueEnum = 'REFERENCE_ID_REQUIRED'


