/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The details of the refund status.
 * @export
 * @interface RefundStatusDetails
 */
export interface RefundStatusDetails {
    /**
     * The reason why the refund has the `PENDING` or `FAILED` status.
     * @type {string}
     * @memberof RefundStatusDetails
     */
    'reason'?: RefundStatusDetailsReasonEnum;
}

type RefundStatusDetailsReasonEnum = 'ECHECK'


