/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RETURNURLREQUIRED
 */
export interface RETURNURLREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof RETURNURLREQUIRED
     */
    'description'?: RETURNURLREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof RETURNURLREQUIRED
     */
    'issue'?: RETURNURLREQUIREDIssueEnum;
}

type RETURNURLREQUIREDDescriptionEnum = 'The return url is required when attempting to vault this source.'
type RETURNURLREQUIREDIssueEnum = 'RETURN_URL_REQUIRED'


