/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SAVEORDERNOTSUPPORTED
 */
export interface SAVEORDERNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof SAVEORDERNOTSUPPORTED
     */
    'description'?: SAVEORDERNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof SAVEORDERNOTSUPPORTED
     */
    'issue'?: SAVEORDERNOTSUPPORTEDIssueEnum;
}

type SAVEORDERNOTSUPPORTEDDescriptionEnum = 'The API caller account is setup in a way that does not allow it to be used for saving the order. This functionality is not available for PayPal Commerce Platform for Platforms & Marketplaces.'
type SAVEORDERNOTSUPPORTEDIssueEnum = 'SAVE_ORDER_NOT_SUPPORTED'


