/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExchangeRate } from './exchange-rate';
import { Money } from './money';
import { PlatformFee } from './platform-fee';

/**
 * The detailed breakdown of the capture activity. This is not available for transactions that are in pending state.
 * @export
 * @interface SellerReceivableBreakdown
 */
export interface SellerReceivableBreakdown {
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'gross_amount': Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'paypal_fee'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'paypal_fee_in_receivable_currency'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'net_amount'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'receivable_amount'?: Money;
    /**
     * 
     * @type {ExchangeRate}
     * @memberof SellerReceivableBreakdown
     */
    'exchange_rate'?: ExchangeRate;
    /**
     * An array of platform or partner fees, commissions, or brokerage fees that associated with the captured payment.
     * @type {Array<PlatformFee>}
     * @memberof SellerReceivableBreakdown
     */
    'platform_fees'?: Array<PlatformFee>;
}

