/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { ShippingType } from './shipping-type';

/**
 * The options that the payee or merchant offers to the payer to ship or pick up their items.
 * @export
 * @interface ShippingOption
 */
export interface ShippingOption {
    /**
     * A unique ID that identifies a payer-selected shipping option.
     * @type {string}
     * @memberof ShippingOption
     */
    'id': string;
    /**
     * A description that the payer sees, which helps them choose an appropriate shipping option. For example, `Free Shipping`, `USPS Priority Shipping`, `Expédition prioritaire USPS`, or `USPS yōuxiān fā huò`. Localize this description to the payer\'s locale.
     * @type {string}
     * @memberof ShippingOption
     */
    'label': string;
    /**
     * A classification for the method of purchase fulfillment.
     * @type {ShippingType}
     * @memberof ShippingOption
     */
    'type'?: ShippingType;
    /**
     * 
     * @type {Money}
     * @memberof ShippingOption
     */
    'amount'?: Money;
    /**
     * If the API request sets `selected = true`, it represents the shipping option that the payee or merchant expects to be pre-selected for the payer when they first view the `shipping.options` in the PayPal Checkout experience. As part of the response if a `shipping.option` contains `selected=true`, it represents the shipping option that the payer selected during the course of checkout with PayPal. Only one `shipping.option` can be set to `selected=true`.
     * @type {boolean}
     * @memberof ShippingOption
     */
    'selected': boolean;
}

