/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SHIPPINGTYPENOTSUPPORTEDFORCLIENT
 */
export interface SHIPPINGTYPENOTSUPPORTEDFORCLIENT {
    /**
     * 
     * @type {string}
     * @memberof SHIPPINGTYPENOTSUPPORTEDFORCLIENT
     */
    'description'?: SHIPPINGTYPENOTSUPPORTEDFORCLIENTDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof SHIPPINGTYPENOTSUPPORTEDFORCLIENT
     */
    'issue'?: SHIPPINGTYPENOTSUPPORTEDFORCLIENTIssueEnum;
}

type SHIPPINGTYPENOTSUPPORTEDFORCLIENTDescriptionEnum = 'The API Caller account is not setup to be able to support a `shipping.type`=`PICKUP_IN_PERSON`. This feature is only supported for <a href=\"https://www.paypal.com/us/business/platforms-and-marketplaces\">PayPal Commerce Platform for Platforms and Marketplaces</a>.'
type SHIPPINGTYPENOTSUPPORTEDFORCLIENTIssueEnum = 'SHIPPING_TYPE_NOT_SUPPORTED_FOR_CLIENT'


