/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressPortable } from './address-portable';
import { Name } from './name';
import { ShippingOption } from './shipping-option';

/**
 * The shipping details.
 * @export
 * @interface ShippingDetail
 */
export interface ShippingDetail {
    /**
     * 
     * @type {Name}
     * @memberof ShippingDetail
     */
    'name'?: Name;
    /**
     * A classification for the method of purchase fulfillment (e.g shipping, in-store pickup, etc). Either `type` or `options` may be present, but not both.
     * @type {string}
     * @memberof ShippingDetail
     */
    'type'?: ShippingDetailTypeEnum;
    /**
     * An array of shipping options that the payee or merchant offers to the payer to ship or pick up their items.
     * @type {Array<ShippingOption>}
     * @memberof ShippingDetail
     */
    'options'?: Array<ShippingOption>;
    /**
     * 
     * @type {AddressPortable}
     * @memberof ShippingDetail
     */
    'address'?: AddressPortable;
}

type ShippingDetailTypeEnum = 'SHIPPING' | 'PICKUP_IN_PERSON' | 'PICKUP_IN_STORE' | 'PICKUP_FROM_PERSON'


