/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SHIPPINGOPTIONSNOTSUPPORTED
 */
export interface SHIPPINGOPTIONSNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof SHIPPINGOPTIONSNOTSUPPORTED
     */
    'description'?: SHIPPINGOPTIONSNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof SHIPPINGOPTIONSNOTSUPPORTED
     */
    'issue'?: SHIPPINGOPTIONSNOTSUPPORTEDIssueEnum;
}

type SHIPPINGOPTIONSNOTSUPPORTEDDescriptionEnum = 'Shipping options are not supported when `shipping.type` is specified or when \'application_context.shipping_preference\' is set as \'NO_SHIPPING\' or \'SET_PROVIDED_ADDRESS\'.'
type SHIPPINGOPTIONSNOTSUPPORTEDIssueEnum = 'SHIPPING_OPTIONS_NOT_SUPPORTED'


