/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SHIPPINGOPTIONSNOTSUPPORTED1
 */
export interface SHIPPINGOPTIONSNOTSUPPORTED1 {
    /**
     * 
     * @type {string}
     * @memberof SHIPPINGOPTIONSNOTSUPPORTED1
     */
    'description'?: SHIPPINGOPTIONSNOTSUPPORTED1DescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof SHIPPINGOPTIONSNOTSUPPORTED1
     */
    'issue'?: SHIPPINGOPTIONSNOTSUPPORTED1IssueEnum;
}

type SHIPPINGOPTIONSNOTSUPPORTED1DescriptionEnum = 'Shipping options are not supported when \'application_context.shipping_preference\' is set as \'NO_SHIPPING\' or \'SET_PROVIDED_ADDRESS\'.'
type SHIPPINGOPTIONSNOTSUPPORTED1IssueEnum = 'SHIPPING_OPTIONS_NOT_SUPPORTED'


