/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Indicates if this is a `first` or `subsequent` payment using a stored payment source (also referred to as stored credential or card on file).
 * @export
 * @enum {string}
 */
export type StoredPaymentSourceUsageType = 'FIRST' | 'SUBSEQUENT' | 'DERIVED'

