/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Indicates the type of the stored payment_source payment.
 * @export
 * @enum {string}
 */
export type StoredPaymentSourcePaymentType = 'ONE_TIME' | 'RECURRING' | 'UNSCHEDULED'

