/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Defines how and when the payment source gets vaulted.
 * @export
 * @enum {string}
 */
export type StoreInVaultInstruction = 'ON_SUCCESS'

