/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardSupplementaryData } from './card-supplementary-data';

/**
 * Supplementary data about a payment. This object passes information that can be used to improve risk assessments and processing costs, for example, by providing Level 2 and Level 3 payment data.
 * @export
 * @interface SupplementaryData
 */
export interface SupplementaryData {
    /**
     * 
     * @type {CardSupplementaryData}
     * @memberof SupplementaryData
     */
    'card'?: CardSupplementaryData;
}

