/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TAXTOTALMISMATCH
 */
export interface TAXTOTALMISMATCH {
    /**
     * 
     * @type {string}
     * @memberof TAXTOTALMISMATCH
     */
    'description'?: TAXTOTALMISMATCHDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof TAXTOTALMISMATCH
     */
    'issue'?: TAXTOTALMISMATCHIssueEnum;
}

type TAXTOTALMISMATCHDescriptionEnum = 'Should equal sum of (tax * quantity) across all items for a given purchase_unit.'
type TAXTOTALMISMATCHIssueEnum = 'TAX_TOTAL_MISMATCH'


