/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TAXTOTALREQUIRED
 */
export interface TAXTOTALREQUIRED {
    /**
     * 
     * @type {string}
     * @memberof TAXTOTALREQUIRED
     */
    'description'?: TAXTOTALREQUIREDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof TAXTOTALREQUIRED
     */
    'issue'?: TAXTOTALREQUIREDIssueEnum;
}

type TAXTOTALREQUIREDDescriptionEnum = 'If item details are specified (items.tax_total and items.quantity) corresponding amount.breakdown.tax_total is required.'
type TAXTOTALREQUIREDIssueEnum = 'TAX_TOTAL_REQUIRED'


