/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Enrolled } from './enrolled';
import { ParesStatus } from './pares-status';

/**
 * Results of 3D Secure Authentication.
 * @export
 * @interface ThreeDSecureAuthenticationResponse
 */
export interface ThreeDSecureAuthenticationResponse {
    /**
     * Transactions status result identifier. The outcome of the issuer\'s authentication.
     * @type {ParesStatus}
     * @memberof ThreeDSecureAuthenticationResponse
     */
    'authentication_status'?: ParesStatus;
    /**
     * Status of Authentication eligibility.
     * @type {Enrolled}
     * @memberof ThreeDSecureAuthenticationResponse
     */
    'enrollment_status'?: Enrolled;
}

