/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The tokenized payment source to fund a payment.
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * The PayPal-generated ID for the token.
     * @type {string}
     * @memberof Token
     */
    'id': string;
    /**
     * The tokenization method that generated the ID.
     * @type {string}
     * @memberof Token
     */
    'type': TokenTypeEnum;
}

type TokenTypeEnum = 'BILLING_AGREEMENT'


