/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TOKENIDNOTFOUND
 */
export interface TOKENIDNOTFOUND {
    /**
     * 
     * @type {string}
     * @memberof TOKENIDNOTFOUND
     */
    'description'?: TOKENIDNOTFOUNDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof TOKENIDNOTFOUND
     */
    'issue'?: TOKENIDNOTFOUNDIssueEnum;
}

type TOKENIDNOTFOUNDDescriptionEnum = 'Specified token was not found. Verify the token and try the request again.'
type TOKENIDNOTFOUNDIssueEnum = 'TOKEN_ID_NOT_FOUND'


