/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error400 } from './error400';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersTrackersPatch400 } from './orders-trackers-patch400';
import { OrdersTrackersPatch400DetailsInner } from './orders-trackers-patch400-details-inner';

/**
 * @type TrackersUpdateTrackingInfoResponse
 * @export
 */
export type TrackersUpdateTrackingInfoResponse = Error400 & OrdersTrackersPatch400;


