/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error404 } from './error404';
import { ErrorLinkDescription } from './error-link-description';
import { OrdersTrackersPatch404 } from './orders-trackers-patch404';
import { OrdersTrackersPatch404DetailsInner } from './orders-trackers-patch404-details-inner';

/**
 * @type TrackersUpdateTrackingInfo404Response
 * @export
 */
export type TrackersUpdateTrackingInfo404Response = Error404 & OrdersTrackersPatch404;


