/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The details of the items in the shipment.
 * @export
 * @interface TrackerItem
 */
export interface TrackerItem {
    /**
     * The item name or title.
     * @type {string}
     * @memberof TrackerItem
     */
    'name'?: string;
    /**
     * The item quantity. Must be a whole number.
     * @type {string}
     * @memberof TrackerItem
     */
    'quantity'?: string;
    /**
     * The stock keeping unit (SKU) for the item. This can contain unicode characters.
     * @type {string}
     * @memberof TrackerItem
     */
    'sku'?: string;
    /**
     * The URL to the item being purchased. Visible to buyer and used in buyer experiences.
     * @type {string}
     * @memberof TrackerItem
     */
    'url'?: string;
    /**
     * The URL of the item\'s image. File type and size restrictions apply. An image that violates these restrictions will not be honored.
     * @type {string}
     * @memberof TrackerItem
     */
    'image_url'?: string;
    /**
     * 
     * @type {any}
     * @memberof TrackerItem
     */
    'upc'?: any;
}

