/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityTimestamps } from './activity-timestamps';
import { LinkDescription } from './link-description';
import { TrackerAllOf } from './tracker-all-of';
import { TrackerItem } from './tracker-item';

/**
 * @type Tracker
 * The tracking response on creation of tracker.
 * @export
 */
export type Tracker = ActivityTimestamps & TrackerAllOf;


