/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TRANSACTIONBLOCKEDBYPAYEE
 */
export interface TRANSACTIONBLOCKEDBYPAYEE {
    /**
     * 
     * @type {string}
     * @memberof TRANSACTIONBLOCKEDBYPAYEE
     */
    'description'?: TRANSACTIONBLOCKEDBYPAYEEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof TRANSACTIONBLOCKEDBYPAYEE
     */
    'issue'?: TRANSACTIONBLOCKEDBYPAYEEIssueEnum;
}

type TRANSACTIONBLOCKEDBYPAYEEDescriptionEnum = 'Transaction blocked by Payee’s Fraud Protection settings.'
type TRANSACTIONBLOCKEDBYPAYEEIssueEnum = 'TRANSACTION_BLOCKED_BY_PAYEE'


