/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TRANSACTIONLIMITEXCEEDED
 */
export interface TRANSACTIONLIMITEXCEEDED {
    /**
     * 
     * @type {string}
     * @memberof TRANSACTIONLIMITEXCEEDED
     */
    'description'?: TRANSACTIONLIMITEXCEEDEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof TRANSACTIONLIMITEXCEEDED
     */
    'issue'?: TRANSACTIONLIMITEXCEEDEDIssueEnum;
}

type TRANSACTIONLIMITEXCEEDEDDescriptionEnum = 'Total payment amount exceeded transaction limit.'
type TRANSACTIONLIMITEXCEEDEDIssueEnum = 'TRANSACTION_LIMIT_EXCEEDED'


