/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UNSUPPORTEDPROCESSINGINSTRUCTION
 */
export interface UNSUPPORTEDPROCESSINGINSTRUCTION {
    /**
     * 
     * @type {string}
     * @memberof UNSUPPORTEDPROCESSINGINSTRUCTION
     */
    'description'?: UNSUPPORTEDPROCESSINGINSTRUCTIONDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof UNSUPPORTEDPROCESSINGINSTRUCTION
     */
    'issue'?: UNSUPPORTEDPROCESSINGINSTRUCTIONIssueEnum;
}

type UNSUPPORTEDPROCESSINGINSTRUCTIONDescriptionEnum = 'The specified processing_instruction is not supported for the given payment_source. Please refer to https://developer.paypal.com/api/orders/v2/#definition-processing_instruction for the list of payment_source that can be specified with this value.'
type UNSUPPORTEDPROCESSINGINSTRUCTIONIssueEnum = 'UNSUPPORTED_PROCESSING_INSTRUCTION'


