/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UNSUPPORTEDINTENTFORPAYMENTSOURCE
 */
export interface UNSUPPORTEDINTENTFORPAYMENTSOURCE {
    /**
     * 
     * @type {string}
     * @memberof UNSUPPORTEDINTENTFORPAYMENTSOURCE
     */
    'description'?: UNSUPPORTEDINTENTFORPAYMENTSOURCEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof UNSUPPORTEDINTENTFORPAYMENTSOURCE
     */
    'issue'?: UNSUPPORTEDINTENTFORPAYMENTSOURCEIssueEnum;
}

type UNSUPPORTEDINTENTFORPAYMENTSOURCEDescriptionEnum = '`intent=AUTHORIZE` is not supported for the specified payment_source. Only `intent=CAPTURE` is supported.'
type UNSUPPORTEDINTENTFORPAYMENTSOURCEIssueEnum = 'UNSUPPORTED_INTENT_FOR_PAYMENT_SOURCE'


