/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UNSUPPORTEDPATCHPARAMETERVALUE
 */
export interface UNSUPPORTEDPATCHPARAMETERVALUE {
    /**
     * 
     * @type {string}
     * @memberof UNSUPPORTEDPATCHPARAMETERVALUE
     */
    'description'?: UNSUPPORTEDPATCHPARAMETERVALUEDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof UNSUPPORTEDPATCHPARAMETERVALUE
     */
    'issue'?: UNSUPPORTEDPATCHPARAMETERVALUEIssueEnum;
}

type UNSUPPORTEDPATCHPARAMETERVALUEDescriptionEnum = 'The value specified for this field is not currently supported.'
type UNSUPPORTEDPATCHPARAMETERVALUEIssueEnum = 'UNSUPPORTED_PATCH_PARAMETER_VALUE'


