/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StoreInVaultInstruction } from './store-in-vault-instruction';

/**
 * Base vaulting specification. The object can be extended for specific use cases within each payment_source that supports vaulting.
 * @export
 * @interface V3VaultInstructionBase
 */
export interface V3VaultInstructionBase {
    /**
     * Defines how and when the payment source gets vaulted.
     * @type {StoreInVaultInstruction}
     * @memberof V3VaultInstructionBase
     */
    'store_in_vault': StoreInVaultInstruction;
}

