/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VaultVenmoWalletBaseAllOf
 */
export interface VaultVenmoWalletBaseAllOf {
    /**
     * The description displayed to Venmo consumer on the approval flow for Venmo, as well as on the Venmo payment token management experience on Venmo.com.
     * @type {string}
     * @memberof VaultVenmoWalletBaseAllOf
     */
    'description'?: string;
    /**
     * Expected business/pricing model for the billing agreement.
     * @type {string}
     * @memberof VaultVenmoWalletBaseAllOf
     */
    'usage_pattern'?: VaultVenmoWalletBaseAllOfUsagePatternEnum;
    /**
     * The usage type associated with the Venmo payment token.
     * @type {string}
     * @memberof VaultVenmoWalletBaseAllOf
     */
    'usage_type'?: VaultVenmoWalletBaseAllOfUsageTypeEnum;
    /**
     * The customer type associated with the Venmo payment token. This is to indicate whether the customer acting on the merchant / platform is either a business or a consumer.
     * @type {string}
     * @memberof VaultVenmoWalletBaseAllOf
     */
    'customer_type'?: VaultVenmoWalletBaseAllOfCustomerTypeEnum;
    /**
     * Create multiple payment tokens for the same payer, merchant/platform combination. Use this when the customer has not logged in at merchant/platform. The payment token thus generated, can then also be used to create the customer account at merchant/platform. Use this also when multiple payment tokens are required for the same payer, different customer at merchant/platform. This helps to identify customers distinctly even though they may share the same Venmo account.
     * @type {boolean}
     * @memberof VaultVenmoWalletBaseAllOf
     */
    'permit_multiple_payment_tokens'?: boolean;
}

type VaultVenmoWalletBaseAllOfUsagePatternEnum = 'IMMEDIATE' | 'DEFERRED' | 'RECURRING_PREPAID' | 'RECURRING_POSTPAID' | 'THRESHOLD_PREPAID' | 'THRESHOLD_POSTPAID'
type VaultVenmoWalletBaseAllOfUsageTypeEnum = 'MERCHANT' | 'PLATFORM'
type VaultVenmoWalletBaseAllOfCustomerTypeEnum = 'CONSUMER' | 'BUSINESS'


