/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VAULTINSTRUCTIONDUPLICATED
 */
export interface VAULTINSTRUCTIONDUPLICATED {
    /**
     * 
     * @type {string}
     * @memberof VAULTINSTRUCTIONDUPLICATED
     */
    'description'?: VAULTINSTRUCTIONDUPLICATEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof VAULTINSTRUCTIONDUPLICATED
     */
    'issue'?: VAULTINSTRUCTIONDUPLICATEDIssueEnum;
}

type VAULTINSTRUCTIONDUPLICATEDDescriptionEnum = 'Only one vault instruction is allowed. Please use `vault.store_in_vault` to provide vault instruction.'
type VAULTINSTRUCTIONDUPLICATEDIssueEnum = 'VAULT_INSTRUCTION_DUPLICATED'


