/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressPortable2 } from './address-portable2';
import { Name2 } from './name2';
import { Phone2 } from './phone2';
import { VenmoWalletAttributesResponse } from './venmo-wallet-attributes-response';

/**
 * Venmo wallet response.
 * @export
 * @interface VenmoWalletResponse
 */
export interface VenmoWalletResponse {
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof VenmoWalletResponse
     */
    'email_address'?: string;
    /**
     * The PayPal payer ID, which is a masked version of the PayPal account number intended for use with third parties. The account number is reversibly encrypted and a proprietary variant of Base32 is used to encode the result.
     * @type {string}
     * @memberof VenmoWalletResponse
     */
    'account_id'?: string;
    /**
     * The Venmo user name chosen by the user, also know as a Venmo handle.
     * @type {string}
     * @memberof VenmoWalletResponse
     */
    'user_name'?: string;
    /**
     * 
     * @type {Name2}
     * @memberof VenmoWalletResponse
     */
    'name'?: Name2;
    /**
     * 
     * @type {Phone2}
     * @memberof VenmoWalletResponse
     */
    'phone_number'?: Phone2;
    /**
     * 
     * @type {AddressPortable2}
     * @memberof VenmoWalletResponse
     */
    'address'?: AddressPortable2;
    /**
     * 
     * @type {VenmoWalletAttributesResponse}
     * @memberof VenmoWalletResponse
     */
    'attributes'?: VenmoWalletAttributesResponse;
}

