/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VenmoWalletAttributes } from './venmo-wallet-attributes';
import { VenmoWalletExperienceContext } from './venmo-wallet-experience-context';

/**
 * Information needed to pay using Venmo.
 * @export
 * @interface VenmoWalletRequest
 */
export interface VenmoWalletRequest {
    /**
     * The PayPal-generated ID for the vaulted payment source. This ID should be stored on the merchant\'s server so the saved payment source can be used for future transactions.
     * @type {string}
     * @memberof VenmoWalletRequest
     */
    'vault_id'?: string;
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof VenmoWalletRequest
     */
    'email_address'?: string;
    /**
     * 
     * @type {VenmoWalletExperienceContext}
     * @memberof VenmoWalletRequest
     */
    'experience_context'?: VenmoWalletExperienceContext;
    /**
     * 
     * @type {VenmoWalletAttributes}
     * @memberof VenmoWalletRequest
     */
    'attributes'?: VenmoWalletAttributes;
}

