/*
Orders

An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

The version of the OpenAPI document: 2.13


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Customizes the buyer experience during the approval process for payment with Venmo.<blockquote><strong>Note:</strong> Partners and Marketplaces might configure <code>shipping_preference</code> during partner account setup, which overrides the request values.</blockquote>
 * @export
 * @interface VenmoWalletExperienceContext
 */
export interface VenmoWalletExperienceContext {
    /**
     * The business name of the merchant. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof VenmoWalletExperienceContext
     */
    'brand_name'?: string;
    /**
     * The location from which the shipping address is derived.
     * @type {string}
     * @memberof VenmoWalletExperienceContext
     */
    'shipping_preference'?: VenmoWalletExperienceContextShippingPreferenceEnum;
}

type VenmoWalletExperienceContextShippingPreferenceEnum = 'GET_FROM_FILE' | 'NO_SHIPPING' | 'SET_PROVIDED_ADDRESS'


